# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Bridge_circuit.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QListWidgetItem
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QSize

class Bridge_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1371, 705)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    \n"
"    background-color: rgb(234, 234, 234);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-90, -10, 1500, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(50, 75, 97);\n"
"    color: White;\n"
"}")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 60, 844, 561))
        self.label_3.setStyleSheet("QLabel{    \n"
"    background-color: rgb(54, 248, 100, 0.2);\n"
"border-radius:40px;\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1141, 120, 181, 241))
        self.label_4.setStyleSheet("QLabel{\n"
"    \n"
"    \n"
"    background-color: rgb(62, 62, 62);\n"
"border-radius:40px;\n"
"border: 10px solid;\n"
"    \n"
"    border-color: rgb(255, 170, 0);\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(20, 160, 151, 311))
        self.label_31.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: white;\n"
"border-radius:40px;\n"
"border: 2px solid;\n"
"    border-color: rgb(127, 110, 87);\n"
"}")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.pushButton_Lab_Manual = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Lab_Manual.setGeometry(QtCore.QRect(1230, 0, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Lab_Manual.setFont(font)
        self.pushButton_Lab_Manual.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Lab_Manual.setStyleSheet("QPushButton\n"
"{\n"
"border:none;\n"
"color:white;\n"
"    background-color: rgb(127, 110, 87);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(51, 51, 51, 0.5);\n"
"}")
        self.pushButton_Lab_Manual.setObjectName("pushButton_Lab_Manual")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(695, 655, 31, 31))
        self.label_22.setStyleSheet("QLabel\n"
"{\n"
"border:none;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("Home_Icon.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1100, 5, 31, 31))
        self.label_2.setStyleSheet("background-color: rgb(50, 75, 97);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("run_icon.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton_Run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Run.setGeometry(QtCore.QRect(1090, 0, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Run.setFont(font)
        self.pushButton_Run.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Run.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(51, 51, 51, 0);\n"
"color:white;\n"
"border:none;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(51, 51, 51, 0.5);\n"
"}")
        self.pushButton_Run.setText("")
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1150, 10, 31, 21))
        self.label_5.setStyleSheet("background-color: rgb(50, 75, 97);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Stop-icon.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setGeometry(QtCore.QRect(1140, 0, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_stop.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(51, 51, 51, 0);\n"
"color:white;\n"
"border:none;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(51, 51, 51, 0.5);\n"
"}")
        self.pushButton_stop.setText("")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.Multimeter_value_displayer = QtWidgets.QLabel(self.centralwidget)
        self.Multimeter_value_displayer.setGeometry(QtCore.QRect(1161, 140, 141, 91))
        self.Multimeter_value_displayer.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: white;\n"
"border-radius:20px;\n"
"border: 2px solid;\n"
"    border-color: rgb(127, 110, 87);\n"
"}")
        self.Multimeter_value_displayer.setText("")
        self.Multimeter_value_displayer.setObjectName("Multimeter_value_displayer")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1155, 290, 30, 30))
        self.label_11.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: black;\n"
"border-radius:15px;\n"
"border: 4px solid;\n"
"    border-color: rgb(127, 110, 87);\n"
"}")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1195, 290, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: black;\n"
"border-radius:15px;\n"
"border: 4px solid;\n"
"    border-color: rgb(127, 110, 87);\n"
"}")
        self.label_12.setText("")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(1235, 290, 30, 30))
        self.label_13.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: black;\n"
"border-radius:15px;\n"
"border: 4px solid;\n"
"    border-color: rgb(127, 110, 87);\n"
"}")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(1275, 290, 30, 30))
        self.label_14.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: black;\n"
"border-radius:15px;\n"
"border: 4px solid;\n"
"    border-color: rgb(127, 110, 87);\n"
"}")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(1154, 260, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(1234, 260, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(1194, 260, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.Voltage_Measurement_port = QtWidgets.QLabel(self.centralwidget)
        self.Voltage_Measurement_port.setGeometry(QtCore.QRect(1162, 297, 16, 16))
        self.Voltage_Measurement_port.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: black;\n"
"border-radius:8px;\n"
"border: 4px solid;\n"
"    \n"
"    border-color: rgb(85, 0, 0);\n"
"}")
        self.Voltage_Measurement_port.setText("")
        self.Voltage_Measurement_port.setObjectName("Voltage_Measurement_port")
        self.current_measurement_port = QtWidgets.QLabel(self.centralwidget)
        self.current_measurement_port.setGeometry(QtCore.QRect(1202, 297, 16, 16))
        self.current_measurement_port.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: black;\n"
"border-radius:8px;\n"
"border: 4px solid;\n"
"    \n"
"    border-color: rgb(85, 0, 0);\n"
"}")
        self.current_measurement_port.setText("")
        self.current_measurement_port.setObjectName("current_measurement_port")
        self.resistance_measurement_port = QtWidgets.QLabel(self.centralwidget)
        self.resistance_measurement_port.setGeometry(QtCore.QRect(1242, 297, 16, 16))
        self.resistance_measurement_port.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: black;\n"
"border-radius:8px;\n"
"border: 4px solid;\n"
"    \n"
"    border-color: rgb(85, 0, 0);\n"
"}")
        self.resistance_measurement_port.setText("")
        self.resistance_measurement_port.setObjectName("resistance_measurement_port")
        self.Common_port = QtWidgets.QLabel(self.centralwidget)
        self.Common_port.setGeometry(QtCore.QRect(1282, 297, 16, 16))
        self.Common_port.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: black;\n"
"border-radius:8px;\n"
"border: 4px solid;\n"
"    \n"
"    border-color: rgb(170, 113, 0);\n"
"}")
        self.Common_port.setText("")
        self.Common_port.setObjectName("Common_port")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(1267, 260, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.R1_value = QtWidgets.QLineEdit(self.centralwidget)
        self.R1_value.setGeometry(QtCore.QRect(630, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.R1_value.setFont(font)
        self.R1_value.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}")
        self.R1_value.setText("")
        self.R1_value.setObjectName("R1_value")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(450, 530, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("background-color: rgb(198, 237, 207);\n"
"color: rgb(71, 0, 0);")
        self.label_32.setObjectName("label_32")
        self.listWidget_Drag_Bridge = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_Drag_Bridge.setGeometry(QtCore.QRect(45, 200, 105, 111))
        self.listWidget_Drag_Bridge.setStyleSheet("QListWidget{\n"
"border: 1px solid;\n"
"border-right-color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"border-top-color: rgb(255, 255, 255);\n"
"border-left-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.listWidget_Drag_Bridge.setObjectName("listWidget_Drag_Bridge")
        self.listWidget_Drag_V1 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_Drag_V1.setGeometry(QtCore.QRect(70, 345, 61, 81))
        self.listWidget_Drag_V1.setStyleSheet("QListWidget{\n"
"border: 1px solid;\n"
"border-right-color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"border-top-color: rgb(255, 255, 255);\n"
"border-left-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.listWidget_Drag_V1.setObjectName("listWidget_Drag_V1")
        self.listWidget_Drop_V1 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_Drop_V1.setGeometry(QtCore.QRect(489, 255, 64, 100))
        self.listWidget_Drop_V1.setStyleSheet("QListWidget{\n"
"border-radius: 20px;\n"
"border: 2px dashed;\n"
"border-color: rgb(170, 125, 111, 0.2);\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.listWidget_Drop_V1.setObjectName("listWidget_Drop_V1")
        self.listWidget_Drop_Bridge = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_Drop_Bridge.setEnabled(True)
        self.listWidget_Drop_Bridge.setGeometry(QtCore.QRect(702, 208, 187, 175))
        self.listWidget_Drop_Bridge.setStyleSheet("QListWidget{\n"
"border: 2px dashed;\n"
"border-color: rgb(170, 125, 111, 0.2);\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.listWidget_Drop_Bridge.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget_Drop_Bridge.setObjectName("listWidget_Drop_Bridge")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(460, 290, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(198, 237, 207);\n"
"color: rgb(71, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.R2_value = QtWidgets.QLineEdit(self.centralwidget)
        self.R2_value.setGeometry(QtCore.QRect(630, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.R2_value.setFont(font)
        self.R2_value.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}")
        self.R2_value.setText("")
        self.R2_value.setObjectName("R2_value")
        self.V2_value = QtWidgets.QLineEdit(self.centralwidget)
        self.V2_value.setGeometry(QtCore.QRect(630, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.V2_value.setFont(font)
        self.V2_value.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}")
        self.V2_value.setText("")
        self.V2_value.setObjectName("V2_value")
        self.R3_value = QtWidgets.QLineEdit(self.centralwidget)
        self.R3_value.setGeometry(QtCore.QRect(630, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.R3_value.setFont(font)
        self.R3_value.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}")
        self.R3_value.setText("")
        self.R3_value.setObjectName("R3_value")
        self.V1_value = QtWidgets.QLineEdit(self.centralwidget)
        self.V1_value.setGeometry(QtCore.QRect(630, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.V1_value.setFont(font)
        self.V1_value.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}")
        self.V1_value.setText("")
        self.V1_value.setObjectName("V1_value")
        self.Bridge_top_label = QtWidgets.QPushButton(self.centralwidget)
        self.Bridge_top_label.setGeometry(QtCore.QRect(770, 175, 36, 36))
        self.Bridge_top_label.setStyleSheet("QPushButton{\n"
"border-radius: 18px;\n"
"border: 2px dashed;\n"
"border-color: rgb(170, 125, 111, 0.2);\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.Bridge_top_label.setText("")
        self.Bridge_top_label.setObjectName("Bridge_top_label")
        self.V1_bottom_label = QtWidgets.QPushButton(self.centralwidget)
        self.V1_bottom_label.setGeometry(QtCore.QRect(500, 350, 36, 36))
        self.V1_bottom_label.setStyleSheet("QPushButton{\n"
"border-radius: 18px;\n"
"border: 2px dashed;\n"
"border-color: rgb(170, 125, 111, 0.2);\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.V1_bottom_label.setText("")
        self.V1_bottom_label.setObjectName("V1_bottom_label")
        self.Bridge_bottom_label = QtWidgets.QPushButton(self.centralwidget)
        self.Bridge_bottom_label.setGeometry(QtCore.QRect(780, 383, 36, 36))
        self.Bridge_bottom_label.setStyleSheet("QPushButton{\n"
"border-radius: 18px;\n"
"border: 2px dashed;\n"
"border-color: rgb(170, 125, 111, 0.2);\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.Bridge_bottom_label.setText("")
        self.Bridge_bottom_label.setObjectName("Bridge_bottom_label")
        self.V1_top_label = QtWidgets.QPushButton(self.centralwidget)
        self.V1_top_label.setGeometry(QtCore.QRect(501, 220, 36, 36))
        self.V1_top_label.setStyleSheet("QPushButton{\n"
"border-radius: 18px;\n"
"border: 2px dashed;\n"
"border-color: rgb(170, 125, 111, 0.2);\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.V1_top_label.setText("")
        self.V1_top_label.setObjectName("V1_top_label")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(515, 446, 284, 7))
        self.label_16.setStyleSheet("background-color: rgb(200, 136, 91);\n"
"border-radius:3px;")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(515, 155, 7, 105))
        self.label_24.setStyleSheet("background-color: rgb(200, 136, 91);\n"
"border-radius:3px;")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(784, 155, 7, 60))
        self.label_25.setStyleSheet("background-color: rgb(200, 136, 91);\n"
"border-radius:3px;")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.pushButton_Ok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Ok.setGeometry(QtCore.QRect(780, 530, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_Ok.setFont(font)
        self.pushButton_Ok.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_Ok.setObjectName("pushButton_Ok")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(515, 347, 7, 105))
        self.label_28.setStyleSheet("background-color: rgb(200, 136, 91);\n"
"border-radius:3px;")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(516, 155, 271, 7))
        self.label_29.setStyleSheet("background-color: rgb(200, 136, 91);\n"
"border-radius:3px;")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(793, 372, 7, 80))
        self.label_36.setStyleSheet("background-color: rgb(200, 136, 91);\n"
"border-radius:3px;")
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.pushButton_Home = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Home.setGeometry(QtCore.QRect(690, 650, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Home.setFont(font)
        self.pushButton_Home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Home.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(51, 51, 51, 0);\n"
"color:white;\n"
"border:none;\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(51, 51, 51, 0.5);\n"
"}")
        self.pushButton_Home.setText("")
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(770, 280, 41, 31))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(198, 237, 207, 0);\n"
"}\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_R1_2_Top = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_R1_2_Top.setGeometry(QtCore.QRect(730, 310, 41, 41))
        self.pushButton_R1_2_Top.setStyleSheet("\n"
"border-radius: 20px;\n"
"background-color: rgb(198, 237, 207, 0);\n"
"")
        self.pushButton_R1_2_Top.setText("")
        self.pushButton_R1_2_Top.setObjectName("pushButton_R1_2_Top")
        self.pushButton_Rx_2_Top = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Rx_2_Top.setGeometry(QtCore.QRect(810, 310, 41, 41))
        self.pushButton_Rx_2_Top.setStyleSheet("\n"
"border-radius: 20px;\n"
"background-color: rgb(198, 237, 207, 0);\n"
"")
        self.pushButton_Rx_2_Top.setText("")
        self.pushButton_Rx_2_Top.setObjectName("pushButton_Rx_2_Top")
        self.pushButton_R2_2_Top = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_R2_2_Top.setGeometry(QtCore.QRect(730, 240, 41, 41))
        self.pushButton_R2_2_Top.setStyleSheet("\n"
"border-radius: 20px;\n"
"background-color: rgb(198, 237, 207, 0);\n"
"")
        self.pushButton_R2_2_Top.setText("")
        self.pushButton_R2_2_Top.setObjectName("pushButton_R2_2_Top")
        self.pushButton_R3_2_Top = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_R3_2_Top.setGeometry(QtCore.QRect(810, 240, 41, 41))
        self.pushButton_R3_2_Top.setStyleSheet("\n"
"border-radius: 20px;\n"
"background-color: rgb(198, 237, 207, 0);\n"
"")
        self.pushButton_R3_2_Top.setText("")
        self.pushButton_R3_2_Top.setObjectName("pushButton_R3_2_Top")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(710, 220, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(198, 237, 207);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.R3_Result = QtWidgets.QPushButton(self.centralwidget)
        self.R3_Result.setGeometry(QtCore.QRect(840, 220, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.R3_Result.setFont(font)
        self.R3_Result.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(198, 237, 207);\n"
"}")
        self.R3_Result.setObjectName("R3_Result")
        self.R2_Result = QtWidgets.QPushButton(self.centralwidget)
        self.R2_Result.setGeometry(QtCore.QRect(710, 350, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.R2_Result.setFont(font)
        self.R2_Result.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(198, 237, 207);\n"
"}")
        self.R2_Result.setObjectName("R2_Result")
        self.Rx_Result = QtWidgets.QPushButton(self.centralwidget)
        self.Rx_Result.setGeometry(QtCore.QRect(830, 350, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Rx_Result.setFont(font)
        self.Rx_Result.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(198, 237, 207);\n"
"}")
        self.Rx_Result.setObjectName("Rx_Result")
        self.label_3.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_31.raise_()
        self.pushButton_Lab_Manual.raise_()
        self.label_22.raise_()
        self.label_2.raise_()
        self.pushButton_Run.raise_()
        self.label_5.raise_()
        self.pushButton_stop.raise_()
        self.Multimeter_value_displayer.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.Voltage_Measurement_port.raise_()
        self.current_measurement_port.raise_()
        self.resistance_measurement_port.raise_()
        self.Common_port.raise_()
        self.label_19.raise_()
        self.R1_value.raise_()
        self.label_32.raise_()
        self.listWidget_Drag_Bridge.raise_()
        self.listWidget_Drag_V1.raise_()
        self.listWidget_Drop_V1.raise_()
        self.listWidget_Drop_Bridge.raise_()
        self.label_8.raise_()
        self.R2_value.raise_()
        self.V2_value.raise_()
        self.R3_value.raise_()
        self.V1_value.raise_()
        self.Bridge_top_label.raise_()
        self.V1_bottom_label.raise_()
        self.Bridge_bottom_label.raise_()
        self.V1_top_label.raise_()
        self.label_16.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.pushButton_Ok.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_36.raise_()
        self.pushButton_Home.raise_()
        self.pushButton_R1_2_Top.raise_()
        self.pushButton_Rx_2_Top.raise_()
        self.pushButton_R2_2_Top.raise_()
        self.pushButton.raise_()
        self.pushButton_R3_2_Top.raise_()
        self.pushButton_2.raise_()
        self.R3_Result.raise_()
        self.R2_Result.raise_()
        self.Rx_Result.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.label_24.hide()
        self.label_29.hide()
        self.label_25.hide()
        self.label_28.hide()
        self.label_16.hide()
        self.label_36.hide()
        bridge = QListWidgetItem(QIcon("Bridge_Circuit.PNG"), "")
        self.listWidget_Drag_Bridge.insertItem(1, bridge)
        self.listWidget_Drag_Bridge.setIconSize(QSize(90, 150))
        C1 = QListWidgetItem(QIcon("Battery_icon.png"), "")
        self.listWidget_Drag_V1.insertItem(1, C1)
        self.listWidget_Drag_V1.setIconSize(QSize(85, 75))

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_Ok.clicked.connect(self.assign_Values)
        self.listWidget_Drag_Bridge.setDragEnabled(True)
        self.listWidget_Drag_V1.setDragEnabled(True)
        self.listWidget_Drop_Bridge.setAcceptDrops(True)
        self.listWidget_Drop_V1.setAcceptDrops(True)
        self.listWidget_Drop_Bridge.setIconSize(QSize(170, 280))
        self.listWidget_Drop_V1.setIconSize(QSize(130, 89))

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_Ok.clicked.connect(self.assign_Values)
        self.listWidget_Drag_Bridge.setDragEnabled(True)
        self.listWidget_Drag_V1.setDragEnabled(True)
        self.listWidget_Drop_Bridge.setAcceptDrops(True)
        self.listWidget_Drop_V1.setAcceptDrops(True)
        self.listWidget_Drop_Bridge.setIconSize(QSize(170, 280))
        self.listWidget_Drop_V1.setIconSize(QSize(130, 89))
        self.listWidget_Drop_V1.clicked.connect(self.set_V1_value)
        # self.pushButton_Run.clicked.connect(self.simulate)
        self.pushButton_R1_2_Top.clicked.connect(self.set_R1_value)
        self.pushButton_R2_2_Top.clicked.connect(self.set_R2_value)
        self.pushButton_R3_2_Top.clicked.connect(self.set_R3_value)
        self.pushButton_Rx_2_Top.clicked.connect(self.set_Rx_value)
        self.listWidget_Drop_V1.clicked.connect(self.set_V1_value)
        # self.pushButton_R1_2.doubleClicked.connect(self.showR1properties)
        self.V1_top_label.clicked.connect(lambda: self.set_button_value(1))
        self.Bridge_top_label.clicked.connect(lambda: self.set_button_value(2))
        self.V1_bottom_label.clicked.connect(lambda: self.set_button_value(3))
        self.Bridge_bottom_label.clicked.connect(lambda: self.set_button_value(4))
        self.listWidget_Drop_Bridge.clicked.connect(self.raised)
        self.counter = 0
        self.pushButton_2.clicked.connect(self.showR1properties)
        self.Rx_Result.clicked.connect(self.showRxproperties)
        self.R2_Result.clicked.connect(self.showR2properties)
        self.R3_Result.clicked.connect(self.showR3properties)
        self.pushButton.clicked.connect(self.showLoadproperties)
        self.pushButton_Run.clicked.connect(self.simulate)

    def raised(self):
            self.pushButton_R1_2.raise_()
            self.pushButton_R2_2.raise_()
            self.pushButton_R3_2.raise_()
            self.pushButton_Rx_2.raise_()

    def set_button_value(self, c):
            if c == 1:
                    self.V1_top_label = 1
            elif c == 2:
                    self.Bridge_top_label = 1
            if c == 3:
                    self.V1_bottom_label = 1

            elif c == 4:
                    self.Bridge_bottom_label = 1

            self.all_button_clicked()

    def all_button_clicked(self):
            if self.V1_top_label == 1 and self.Bridge_top_label == 1:
                    self.label_24.show()
                    self.label_29.show()
                    self.label_25.show()
            if self.V1_bottom_label == 1 and self.Bridge_bottom_label == 1:
                    self.label_28.show()
                    self.label_16.show()
                    self.label_36.show()

    def set_V1_value(self):
            self.V1_value.show()
            self.R1_value.hide()
            self.R2_value.hide()
            self.V2_value.hide()
            self.R3_value.hide()
            self.counter = 2

    def set_R2_value(self):
            self.V1_value.hide()
            self.R1_value.show()
            self.R2_value.hide()
            self.V2_value.hide()
            self.R3_value.hide()
            self.counter = 3

    def set_R1_value(self):
            self.V1_value.hide()
            self.R1_value.hide()
            self.R2_value.show()
            self.V2_value.hide()
            self.R3_value.hide()
            self.counter = 4

    def set_R3_value(self):
            self.V1_value.hide()
            self.R1_value.hide()
            self.R2_value.hide()
            self.V2_value.show()
            self.R3_value.hide()
            self.counter = 5

    def set_Rx_value(self):
            self.V1_value.hide()
            self.R1_value.hide()
            self.R2_value.hide()
            self.V2_value.hide()
            self.R3_value.show()
            self.counter = 6


    def showR1properties(self):
         R1 = float(self.r1)
         R2 = float(self.r2)
         Vs = float(self.v1)
         V1 = (R1/(R2+R1))*Vs
         I = V1/R1

         self.Multimeter_value_displayer.setText(" R1 = {0}Ω \n V1 = {1}V \n I = {2}A".format(self.R1_value.text(), round(V1, 3) , round(I, 3)))

    def showR3properties(self):

         Rx = float(self.rx)
         R3 = float(self.r3)
         Vs = float(self.v1)
         V1 = (R3/(Rx+R3))*Vs
         I = V1/R3

         self.Multimeter_value_displayer.setText(" R1 = {0}Ω \n V1 = {1}V \n I1 = {2}A".format(self.V2_value.text(), round(V1, 3) , round(I, 3)))

    def showRxproperties(self):

         Rx = float(self.rx)
         R3 = float(self.r3)
         Vs = float(self.v1)
         V1 = (Rx/(Rx+R3))*Vs
         I = V1/Rx

         self.Multimeter_value_displayer.setText(" R1 = {0}Ω \n V1 = {1}V \n I1 = {2}A".format(self.R3_value.text(), round(V1, 3) , round(I, 3)))

    def showR2properties(self):
            R1 = float(self.r1)
            R2 = float(self.r2)
            Vs = float(self.v1)
            V1 = (R2 / (R2 + R1)) * Vs
            I = V1 / R2

            self.Multimeter_value_displayer.setText(" R3 = {0}Ω \n V3 = {1}V \n I3 = {2}A".format(self.R2_value.text(), round(V1, 3) , round(I, 3)))

    def showLoadproperties(self):
            R1 = float(self.r1)
            R2 = float(self.r2)
            Rx = float(self.rx)
            R3 = float(self.r3)
            Vs = float(self.v1)
            VA = (R2 / (R2 + R1)) * Vs
            VB = (Rx / (Rx + R3)) * Vs
            V1 = VA - VB

            self.Multimeter_value_displayer.setText("VAB = {0}V ".format(round(V1, 3)))

    def assign_Values(self):

            self.v1 = self.V1_value.text()
            self.r1 = self.R1_value.text()
            self.r2 = self.R2_value.text()
            self.r3 = self.V2_value.text()
            self.rx = self.R3_value.text()

    def simulate(self):

            if self.V1_top_label == 1 and self.Bridge_top_label == 1 and self.V1_bottom_label == 1 and self.Bridge_bottom_label == 1:
                    self.label.setText(
                            "                         Wheatstone Bridge Circuit        ")
                    self.label.setStyleSheet("QLabel{\n"
                                             "    \n"
                                             "    background-color: rgb(50, 75, 97);\n"
                                             "    color: white;\n"
                                             "}")
            else:
                    self.label.setText(
                            "                           (Circuit Not Complete)")
                    self.label.setStyleSheet("QLabel{\n"
                                             "    \n"
                                             "    background-color: rgb(50, 75, 97);\n"
                                             "    color: red;\n"
                                             "}")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bridge Circuit"))
        self.label.setText(_translate("MainWindow", "                          Wheatstone Bridge Circuit"))
        self.pushButton_Lab_Manual.setText(_translate("MainWindow", "Lab Manual"))
        self.label_15.setText(_translate("MainWindow", "V"))
        self.label_17.setText(_translate("MainWindow", "R"))
        self.label_18.setText(_translate("MainWindow", "A"))
        self.label_19.setText(_translate("MainWindow", "COM"))
        self.R1_value.setPlaceholderText(_translate("MainWindow", "  Enter R1 Value"))
        self.label_32.setText(_translate("MainWindow", "Click a component to \n""change its value"))
        self.label_8.setText(_translate("MainWindow", "V1"))
        self.R2_value.setPlaceholderText(_translate("MainWindow", "  Enter R2 Value"))
        self.V2_value.setPlaceholderText(_translate("MainWindow", "  Enter R3 Value"))
        self.R3_value.setPlaceholderText(_translate("MainWindow", "  Enter Rx Value"))
        self.V1_value.setPlaceholderText(_translate("MainWindow", "  Enter V1 Value"))
        self.pushButton_Ok.setText(_translate("MainWindow", "Ok"))
        self.pushButton_2.setText(_translate("MainWindow", "R1"))
        self.R3_Result.setText(_translate("MainWindow", "R3"))
        self.R2_Result.setText(_translate("MainWindow", "R2"))
        self.Rx_Result.setText(_translate("MainWindow", "Rx"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Bridge_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
