# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Current_flow_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import time

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 80, 10, 10))
        self.label.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 80, 10, 10))
        self.label_2.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 80, 10, 10))
        self.label_3.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 80, 10, 10))
        self.label_4.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 80, 10, 10))
        self.label_5.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 80, 10, 10))
        self.label_6.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(270, 80, 10, 10))
        self.label_7.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(290, 80, 10, 10))
        self.label_8.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(310, 80, 10, 10))
        self.label_9.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(330, 80, 10, 10))
        self.label_10.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(350, 80, 10, 10))
        self.label_11.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(370, 80, 10, 10))
        self.label_12.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(390, 80, 10, 10))
        self.label_13.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(410, 80, 10, 10))
        self.label_14.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(430, 80, 10, 10))
        self.label_15.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(450, 80, 10, 10))
        self.label_16.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(450, 100, 10, 10))
        self.label_17.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(450, 120, 10, 10))
        self.label_18.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(450, 140, 10, 10))
        self.label_19.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(450, 160, 10, 10))
        self.label_20.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(450, 180, 10, 10))
        self.label_21.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(450, 200, 10, 10))
        self.label_22.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(450, 220, 10, 10))
        self.label_23.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(450, 240, 10, 10))
        self.label_24.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(450, 260, 10, 10))
        self.label_25.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(390, 260, 10, 10))
        self.label_35.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(170, 260, 10, 10))
        self.label_36.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(190, 260, 10, 10))
        self.label_37.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(250, 260, 10, 10))
        self.label_38.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(430, 260, 10, 10))
        self.label_39.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(290, 260, 10, 10))
        self.label_40.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(210, 260, 10, 10))
        self.label_41.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(310, 260, 10, 10))
        self.label_42.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(410, 260, 10, 10))
        self.label_43.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(270, 260, 10, 10))
        self.label_44.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_44.setText("")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(330, 260, 10, 10))
        self.label_45.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_45.setText("")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(370, 260, 10, 10))
        self.label_46.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(230, 260, 10, 10))
        self.label_48.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(350, 260, 10, 10))
        self.label_49.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(150, 100, 10, 10))
        self.label_26.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(150, 200, 10, 10))
        self.label_27.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(150, 120, 10, 10))
        self.label_28.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(150, 220, 10, 10))
        self.label_29.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(150, 160, 10, 10))
        self.label_30.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(150, 140, 10, 10))
        self.label_31.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(150, 180, 10, 10))
        self.label_33.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(150, 240, 10, 10))
        self.label_34.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(150, 260, 10, 10))
        self.label_50.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_50.setText("")
        self.label_50.setObjectName("label_50")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(300, 160, 10, 10))
        self.label_47.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_47.setText("")
        self.label_47.setObjectName("label_47")
        self.label_52 = QtWidgets.QLabel(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(300, 180, 10, 10))
        self.label_52.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_52.setText("")
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(300, 120, 10, 10))
        self.label_53.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_53.setText("")
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(300, 100, 10, 10))
        self.label_54.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_54.setText("")
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(300, 240, 10, 10))
        self.label_55.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_55.setText("")
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(300, 140, 10, 10))
        self.label_56.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_56.setText("")
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.centralwidget)
        self.label_57.setGeometry(QtCore.QRect(300, 200, 10, 10))
        self.label_57.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_57.setText("")
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.centralwidget)
        self.label_58.setGeometry(QtCore.QRect(300, 220, 10, 10))
        self.label_58.setStyleSheet("QLabel{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.label_58.setText("")
        self.label_58.setObjectName("label_58")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 310, 75, 23))
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(57, 57, 57);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(51, 51, 51, 0.5);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.move_labels)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Enter"))
    def move_labels(self):
        x = self.label_16.x()
        y = self.label_16.y()
        for i in range(150):
                self.label_16.move(x+i, y)
                for j in range(1000):
                        print()
                i += 0.1

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
