# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LabReportpdf.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from reportlab.pdfgen import canvas
from reportlab.platypus import Paragraph, Table, TableStyle, Frame
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(959, 565)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, -5, 961, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(50, 75, 97);\n"
"color:white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 36, 191, 531))
        self.label_2.setStyleSheet("QLabel{\n"
"    \n"
"   background-color: rgb(40, 44, 53);\n"
" \n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_FrontPage = QtWidgets.QPushButton(Dialog)
        self.pushButton_FrontPage.setGeometry(QtCore.QRect(20, 60, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_FrontPage.setFont(font)
        self.pushButton_FrontPage.setStyleSheet("QPushButton\n"
"{\n"
"border:none;\n"
"    background-color: rgb(40, 44, 53);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border:2px solid white;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pushButton_FrontPage.setObjectName("pushButton_FrontPage")
        self.pushButton_Objective = QtWidgets.QPushButton(Dialog)
        self.pushButton_Objective.setGeometry(QtCore.QRect(20, 100, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Objective.setFont(font)
        self.pushButton_Objective.setStyleSheet("QPushButton\n"
"{\n"
"border:none;\n"
"    background-color: rgb(40, 44, 53);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border:2px solid white;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pushButton_Objective.setObjectName("pushButton_Objective")
        self.pushButton_Theory = QtWidgets.QPushButton(Dialog)
        self.pushButton_Theory.setGeometry(QtCore.QRect(20, 140, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Theory.setFont(font)
        self.pushButton_Theory.setStyleSheet("QPushButton\n"
"{\n"
"border:none;\n"
"    background-color: rgb(40, 44, 53);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border:2px solid white;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pushButton_Theory.setObjectName("pushButton_Theory")
        self.pushButton_Calculation = QtWidgets.QPushButton(Dialog)
        self.pushButton_Calculation.setGeometry(QtCore.QRect(20, 220, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Calculation.setFont(font)
        self.pushButton_Calculation.setStyleSheet("QPushButton\n"
"{\n"
"border:none;\n"
"    background-color: rgb(40, 44, 53);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border:2px solid white;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pushButton_Calculation.setObjectName("pushButton_Calculation")
        self.pushButton_Procedure = QtWidgets.QPushButton(Dialog)
        self.pushButton_Procedure.setGeometry(QtCore.QRect(20, 180, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Procedure.setFont(font)
        self.pushButton_Procedure.setStyleSheet("QPushButton\n"
"{\n"
"border:none;\n"
"    background-color: rgb(40, 44, 53);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border:2px solid white;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pushButton_Procedure.setObjectName("pushButton_Procedure")
        self.pushButton_Results = QtWidgets.QPushButton(Dialog)
        self.pushButton_Results.setGeometry(QtCore.QRect(20, 260, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Results.setFont(font)
        self.pushButton_Results.setStyleSheet("QPushButton\n"
"{\n"
"border:none;\n"
"    background-color: rgb(40, 44, 53);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border:2px solid white;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"")
        self.pushButton_Results.setObjectName("pushButton_Results")
        self.pushButton_Conclusion = QtWidgets.QPushButton(Dialog)
        self.pushButton_Conclusion.setGeometry(QtCore.QRect(20, 300, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Conclusion.setFont(font)
        self.pushButton_Conclusion.setStyleSheet("QPushButton\n"
"{\n"
"border:none;\n"
"    background-color: rgb(40, 44, 53);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border:2px solid white;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pushButton_Conclusion.setObjectName("pushButton_Conclusion")
        self.Discussion_TextEdit = QtWidgets.QTextEdit(Dialog)
        self.Discussion_TextEdit.setGeometry(QtCore.QRect(230, 80, 671, 391))
        self.Discussion_TextEdit.setStyleSheet("")
        self.Discussion_TextEdit.setObjectName("Discussion_TextEdit")
        self.Discussion = QtWidgets.QLabel(Dialog)
        self.Discussion.setGeometry(QtCore.QRect(230, 50, 671, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Discussion.setFont(font)
        self.Discussion.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(144, 159, 195);\n"
"    color:white;\n"
"}")
        self.Discussion.setObjectName("Discussion")
        self.Submit = QtWidgets.QPushButton(Dialog)
        self.Submit.setGeometry(QtCore.QRect(230, 490, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Submit.setFont(font)
        self.Submit.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(245, 245, 245);\n"
"border:none;\n"
"background-color: rgb(144, 159, 195);\n"
"border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border:none;\n"
"background-color: rgb(110, 192, 227);\n"
"}\n"
"")
        self.Submit.setObjectName("Submit")
        self.Results_label = QtWidgets.QLabel(Dialog)
        self.Results_label.setGeometry(QtCore.QRect(230, 50, 671, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Results_label.setFont(font)
        self.Results_label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(144, 159, 195);"
"    color:white;\n"
"}")
        self.Results_label.setObjectName("Results_label")
        self.Results_TextEdit = QtWidgets.QTextEdit(Dialog)
        self.Results_TextEdit.setGeometry(QtCore.QRect(230, 80, 671, 391))
        self.Results_TextEdit.setStyleSheet("")
        self.Results_TextEdit.setObjectName("Results_TextEdit")
        self.Calculation_label = QtWidgets.QLabel(Dialog)
        self.Calculation_label.setGeometry(QtCore.QRect(230, 50, 671, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Calculation_label.setFont(font)
        self.Calculation_label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(144, 159, 195);\n"
"    color:white;\n"
"}")
        self.Calculation_label.setObjectName("Calculation_label")
        self.Calculation_TextEdit = QtWidgets.QTextEdit(Dialog)
        self.Calculation_TextEdit.setGeometry(QtCore.QRect(230, 80, 671, 391))
        self.Calculation_TextEdit.setStyleSheet("")
        self.Calculation_TextEdit.setObjectName("Calculation_TextEdit")
        self.Procedure_label = QtWidgets.QLabel(Dialog)
        self.Procedure_label.setGeometry(QtCore.QRect(230, 50, 671, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Procedure_label.setFont(font)
        self.Procedure_label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(144, 159, 195);\n"
"    color:white;\n"
"}")
        self.Procedure_label.setObjectName("Procedure_label")
        self.Procedure_TextEdit = QtWidgets.QTextEdit(Dialog)
        self.Procedure_TextEdit.setGeometry(QtCore.QRect(230, 80, 671, 391))
        self.Procedure_TextEdit.setStyleSheet("")
        self.Procedure_TextEdit.setObjectName("Procedure_TextEdit")
        self.Theory_label = QtWidgets.QLabel(Dialog)
        self.Theory_label.setGeometry(QtCore.QRect(230, 50, 671, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Theory_label.setFont(font)
        self.Theory_label.setStyleSheet("QLabel\n"
"{\n"
"    	background-color: rgb(144, 159, 195);\n"
"    color:white;\n"
"}")
        self.Theory_label.setObjectName("Theory_label")
        self.Theory_TextEdit = QtWidgets.QTextEdit(Dialog)
        self.Theory_TextEdit.setGeometry(QtCore.QRect(230, 80, 671, 391))
        self.Theory_TextEdit.setStyleSheet("")
        self.Theory_TextEdit.setObjectName("Theory_TextEdit")
        self.Equipment_label = QtWidgets.QLabel(Dialog)
        self.Equipment_label.setGeometry(QtCore.QRect(230, 50, 671, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Equipment_label.setFont(font)
        self.Equipment_label.setStyleSheet("QLabel\n"
"{\n"
"    \n"
"    background-color: rgb(144, 159, 195);\n"
"    color:white;\n"
"}")
        self.Equipment_label.setObjectName("Equipment_label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(230, 260, 671, 221))
        self.label_3.setStyleSheet("background-color: rgb(192, 212, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(570, 260, 2, 222))
        self.label_4.setStyleSheet("background-color: white;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(330, 270, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(680, 260, 121, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(250, 300, 71, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(460, 300, 51, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(830, 300, 51, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(740, 300, 31, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(600, 300, 71, 21))
        self.label_11.setObjectName("label_11")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(240, 330, 101, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 390, 101, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(240, 360, 101, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(240, 420, 101, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(240, 450, 101, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(450, 330, 71, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(450, 450, 71, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_8.setGeometry(QtCore.QRect(450, 360, 71, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_9.setGeometry(QtCore.QRect(450, 390, 71, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_10.setGeometry(QtCore.QRect(450, 420, 71, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_11.setGeometry(QtCore.QRect(580, 330, 101, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_12.setGeometry(QtCore.QRect(580, 450, 101, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_13.setGeometry(QtCore.QRect(580, 360, 101, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_14.setGeometry(QtCore.QRect(580, 390, 101, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_15.setGeometry(QtCore.QRect(580, 420, 101, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_16.setGeometry(QtCore.QRect(710, 330, 91, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_17.setGeometry(QtCore.QRect(710, 450, 91, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_18.setGeometry(QtCore.QRect(710, 360, 91, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_19.setGeometry(QtCore.QRect(710, 390, 91, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_20.setGeometry(QtCore.QRect(710, 420, 91, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_21.setGeometry(QtCore.QRect(830, 390, 61, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_22.setGeometry(QtCore.QRect(830, 360, 61, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_23.setGeometry(QtCore.QRect(830, 420, 61, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_24.setGeometry(QtCore.QRect(830, 330, 61, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_25.setGeometry(QtCore.QRect(830, 450, 61, 20))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.Equipment_TextEdit = QtWidgets.QTextEdit(Dialog)
        self.Equipment_TextEdit.setGeometry(QtCore.QRect(230, 80, 671, 181))
        self.Equipment_TextEdit.setStyleSheet("")
        self.Equipment_TextEdit.setObjectName("Equipment_TextEdit")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(230, 50, 671, 431))
        self.label_12.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.Front_page_label = QtWidgets.QLabel(Dialog)
        self.Front_page_label.setGeometry(QtCore.QRect(230, 50, 671, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Front_page_label.setFont(font)
        self.Front_page_label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: ;\n"
"    background-color: rgb(144, 159, 195);\n"
"    color: white;\n"
"}")
        self.Front_page_label.setObjectName("Front_page_label")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(410, 110, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(410, 300, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(410, 140, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(410, 240, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(410, 420, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(410, 380, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(410, 170, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.lineEdit_26 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_26.setGeometry(QtCore.QRect(520, 110, 161, 20))
        self.lineEdit_26.setStyleSheet("QLineEdit\n"
"{\n"
"border:none;\n"
"border-radius:2px;\n"
"}")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_27.setGeometry(QtCore.QRect(520, 140, 161, 20))
        self.lineEdit_27.setStyleSheet("QLineEdit\n"
"{\n"
"border:none;\n"
"border-radius:2px;\n"
"}")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_28.setGeometry(QtCore.QRect(520, 170, 161, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_28.setFont(font)
        self.lineEdit_28.setStyleSheet("QLineEdit\n"
"{\n"
"border:none;\n"
"border-radius:2px;\n"
"}")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_29.setGeometry(QtCore.QRect(520, 240, 161, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_29.setFont(font)
        self.lineEdit_29.setStyleSheet("QLineEdit\n"
"{\n"
"border:none;\n"
"border-radius:2px;\n"
"}")
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_30 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_30.setGeometry(QtCore.QRect(520, 300, 161, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_30.setFont(font)
        self.lineEdit_30.setStyleSheet("QLineEdit\n"
"{\n"
"border:none;\n"
"border-radius:2px;\n"
"}")
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_31.setGeometry(QtCore.QRect(550, 420, 161, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_31.setFont(font)
        self.lineEdit_31.setStyleSheet("QLineEdit\n"
"{\n"
"border:none;\n"
"border-radius:2px;\n"
"}")
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_32.setGeometry(QtCore.QRect(550, 380, 161, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_32.setFont(font)
        self.lineEdit_32.setStyleSheet("QLineEdit\n"
"{\n"
"border:none;\n"
"border-radius:2px;\n"
"}")
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.Front_page_label_2 = QtWidgets.QLabel(Dialog)
        self.Front_page_label_2.setGeometry(QtCore.QRect(330, 90, 471, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Front_page_label_2.setFont(font)
        self.Front_page_label_2.setStyleSheet("QLabel\n"
"{ border-radius: 15px;\n"
"    background-color: white;\n"
"    color:white;\n"
"}")
        self.Front_page_label_2.setText("")
        self.Front_page_label_2.setObjectName("Front_page_label_2")
        self.Front_page_label_7 = QtWidgets.QLabel(Dialog)
        self.Front_page_label_7.setGeometry(QtCore.QRect(330, 220, 471, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Front_page_label_7.setFont(font)
        self.Front_page_label_7.setStyleSheet("QLabel\n"
"{ border-radius: 15px;\n"
"    background-color: white;\n"
"    color:white;\n"
"}")
        self.Front_page_label_7.setText("")
        self.Front_page_label_7.setObjectName("Front_page_label_7")
        self.Front_page_label_8 = QtWidgets.QLabel(Dialog)
        self.Front_page_label_8.setGeometry(QtCore.QRect(330, 350, 471, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Front_page_label_8.setFont(font)
        self.Front_page_label_8.setStyleSheet("QLabel\n"
"{ border-radius: 15px;\n"
"    background-color: white;\n"
"    color:white;\n"
"}")
        self.Front_page_label_8.setText("")
        self.Front_page_label_8.setObjectName("Front_page_label_8")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(410, 270, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.lineEdit_33 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_33.setGeometry(QtCore.QRect(520, 270, 161, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_33.setFont(font)
        self.lineEdit_33.setStyleSheet("QLineEdit\n"
"{\n"
"border:none;\n"
"border-radius:2px;\n"
"}")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.Submit_2 = QtWidgets.QPushButton(Dialog)
        self.Submit_2.setGeometry(QtCore.QRect(800, 490, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Submit_2.setFont(font)
        self.Submit_2.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(245, 245, 245);\n"
"border:none;\n"
"background-color: rgb(144, 159, 195);\n"
"border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border:none;\n"
"background-color: rgb(110, 192, 227);\n"
"}\n"
"")
        self.Submit_2.setObjectName("Submit_2")
        self.lineEdit_34 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_34.setGeometry(QtCore.QRect(642, 489, 151, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_34.setFont(font)
        self.lineEdit_34.setStyleSheet("border:none;\n"
"border-radius:8px;")
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.Equipment_label.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton_FrontPage.raise_()
        self.pushButton_Objective.raise_()
        self.pushButton_Theory.raise_()
        self.pushButton_Calculation.raise_()
        self.pushButton_Procedure.raise_()
        self.pushButton_Results.raise_()
        self.pushButton_Conclusion.raise_()
        self.Discussion_TextEdit.raise_()
        self.Discussion.raise_()
        self.Submit.raise_()
        self.Results_label.raise_()
        self.Results_TextEdit.raise_()
        self.Calculation_label.raise_()
        self.Calculation_TextEdit.raise_()
        self.Procedure_label.raise_()
        self.Procedure_TextEdit.raise_()
        self.Theory_label.raise_()
        self.Theory_TextEdit.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit_7.raise_()
        self.lineEdit_8.raise_()
        self.lineEdit_9.raise_()
        self.lineEdit_10.raise_()
        self.lineEdit_11.raise_()
        self.lineEdit_12.raise_()
        self.lineEdit_13.raise_()
        self.lineEdit_14.raise_()
        self.lineEdit_15.raise_()
        self.lineEdit_16.raise_()
        self.lineEdit_17.raise_()
        self.lineEdit_18.raise_()
        self.lineEdit_19.raise_()
        self.lineEdit_20.raise_()
        self.lineEdit_21.raise_()
        self.lineEdit_22.raise_()
        self.lineEdit_23.raise_()
        self.lineEdit_24.raise_()
        self.lineEdit_25.raise_()
        self.Equipment_TextEdit.raise_()
        self.label_12.raise_()
        self.Front_page_label.raise_()
        self.Front_page_label_2.raise_()
        self.lineEdit_26.raise_()
        self.label_13.raise_()
        self.label_15.raise_()
        self.lineEdit_28.raise_()
        self.label_19.raise_()
        self.Front_page_label_7.raise_()
        self.lineEdit_29.raise_()
        self.label_16.raise_()
        self.lineEdit_30.raise_()
        self.label_14.raise_()
        self.Front_page_label_8.raise_()
        self.label_18.raise_()
        self.lineEdit_32.raise_()
        self.lineEdit_27.raise_()
        self.label_17.raise_()
        self.lineEdit_31.raise_()
        self.label_20.raise_()
        self.lineEdit_33.raise_()
        self.Submit_2.raise_()
        self.lineEdit_34.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.lineEdit_34.hide(), self.Submit_2.hide()
        self.pushButton_FrontPage.clicked.connect(self.show_front_page)
        self.pushButton_Objective.clicked.connect(self.show_Objective_page)
        self.pushButton_Theory.clicked.connect(self.show_Theory_page)
        self.pushButton_Procedure.clicked.connect(self.show_Procedure_page)
        self.pushButton_Calculation.clicked.connect(self.show_calculation_page)
        self.pushButton_Results.clicked.connect(self.show_result_page)
        self.pushButton_Conclusion.clicked.connect(self.show_conclusion_page)
        self.Submit_2.clicked.connect(self.my_pdf)

    def my_pdf(self):

            course_No = self.lineEdit_26.text()
            Experiment_No = self.lineEdit_27.text()
            Title = self.lineEdit_28.text()
            Done_By = self.lineEdit_29.text()
            Group_No = self.lineEdit_30.text()
            date_of_Experiment = self.lineEdit_31.text()
            date_of_Submission = self.lineEdit_32.text()
            objective = self.Equipment_TextEdit.toPlainText()
            file_location = self.lineEdit_34.text()
            ID_No = self.lineEdit_33.text()
            print(objective)
            filename = "C:/Users/Habtamu/Desktop/{}.pdf".format(file_location)
            pdf = canvas.Canvas(filename)
            pdf.setTitle('Lab_Report')
            pdf.setFont('Times-Roman', 28)
            pdf.drawString(160, 700, "Addis Ababa University")
            pdf.setFont('Times-Roman', 26)
            pdf.drawString(110, 650, "Addis Ababa Institute of Technology")
            pdf.setFont('Times-Roman', 22)
            pdf.drawString(70, 610, "School of Electrical and Computer Engineering")

            pdf.drawInlineImage('logo3.png', 30, 730)

            pdf.setFont('Times-Roman', 18)
            pdf.drawString(220, 570, "Labratory Report")

            pdf.setFont('Times-Roman', 14)
            pdf.drawString(40, 480, "Course No:{0}".format(course_No))

            pdf.setFont('Times-Roman', 14)
            pdf.drawString(40, 460, "Experiment No:{0}".format(Experiment_No))

            pdf.setFont('Times-Roman', 16)
            pdf.drawString(140, 410, "Title:{0}".format(Title))

            name = "Abdurehman"
            pdf.setFont('Times-Roman', 14)
            pdf.drawString(40, 340, "By:{0}".format(Done_By))

            pdf.setFont('Times-Roman', 14)
            pdf.drawString(40, 320, "ID No:{0}".format(ID_No))

            pdf.setFont('Times-Roman', 14)
            pdf.drawString(40, 300, "Group:{0}".format(Group_No))

            pdf.setFont('Times-Roman', 14)
            pdf.drawString(40, 280, "Date of Experiment:{0}".format(date_of_Experiment))
            pdf.setFont('Times-Roman', 14)
            pdf.drawString(40, 260, "Date of Submission:{0}".format(date_of_Submission))

            pdf.line(10, 830, 585, 830)
            pdf.line(10, 830, 10, 10)
            pdf.line(585, 830, 585, 10)
            pdf.line(10, 10, 585, 10)
            pdf.showPage()

            pdf.drawString(20, 800, "Objective of the Experiment:")
            Flow_object = []
            paragraph = []
            styles = getSampleStyleSheet()
            p_text = Paragraph(objective, style=styles["Normal"])
            paragraph.append(p_text)

            frame = Frame(50, 600, 500, 160, showBoundary=1)
            frame.addFromList(paragraph, pdf)
            pdf.drawString(50, 440, "Equipment Used:")
            t1 = Paragraph(" ", style=styles["Normal"])
            equi_1 = self.lineEdit.text()
            equi_2 = self.lineEdit_2.text()
            equi_3 = self.lineEdit_3.text()
            equi_4 = self.lineEdit_4.text()
            equi_5 = self.lineEdit_5.text()
            quantity_1 = self.lineEdit_6.text()
            quantity_2 = self.lineEdit_7.text()
            quantity_3 = self.lineEdit_8.text()
            quantity_4 = self.lineEdit_9.text()
            quantity_5 = self.lineEdit_10.text()
            Flow_object.append(t1)
            data = [['No', 'Description', 'Quantity'], ['1', '{0}'.format(equi_1), '{}'.format(quantity_1)], ['2', '{0}'.format(equi_3), '{}'.format(quantity_3)],
                    ['3', '{0}'.format(equi_2), '{}'.format(quantity_4)], ['4', '{0}'.format(equi_4), '{}'.format(quantity_5)], ['5', '{0}'.format(equi_5), '{}'.format(quantity_2)]]
            table = Table(data)
            ta = TableStyle(
                    [("GRID", (0, 0), (-1, -1), 2, colors.black), ("Background", (0, 0), (-1, -1), colors.green)])
            table.setStyle(ta)
            Flow_object.append(table)
            frame = Frame(50, 300, 150, 120, showBoundary=1)
            frame.addFromList(Flow_object, pdf)

            comp_1 = self.lineEdit_11.text()
            comp_2 = self.lineEdit_12.text()
            comp_3 = self.lineEdit_13.text()
            comp_4 = self.lineEdit_14.text()
            comp_5 = self.lineEdit_15.text()
            quantity_1 = self.lineEdit_21.text()
            quantity_2 = self.lineEdit_22.text()
            quantity_3 = self.lineEdit_23.text()
            quantity_4 = self.lineEdit_24.text()
            quantity_5 = self.lineEdit_25.text()
            type_1 =self.lineEdit_16.text()
            type_2 = self.lineEdit_17.text()
            type_3 = self.lineEdit_18.text()
            type_4 = self.lineEdit_19.text()
            type_5 = self.lineEdit_20.text()

            pdf.drawString(340, 440, "Component Used:")
            Flow_object2 = []
            data2 = [['No', 'Description', 'Type', 'Quantity'], ['1', '{}'.format(comp_1), '{}'.format(type_1), '{}'.format(quantity_4)], ['2', '{}'.format(comp_3),'{}'.format(type_3), '{}'.format(quantity_2)],
                    ['3', '{}'.format(comp_4), '{}'.format(type_4),'{}'.format(quantity_1)], ['4', '{}'.format(comp_5), '{}'.format(type_5), '{}'.format(quantity_3)], ['5', '{}'.format(comp_2),'{}'.format(type_2), '{}'.format(quantity_5)]]
            table = Table(data2)
            ta = TableStyle(
                    [("GRID", (0, 0), (-1, -1), 2, colors.black), ("Background", (0, 0), (-1, -1), colors.green)])
            table.setStyle(ta)
            Flow_object2.append(table)
            frame = Frame(330, 300, 200, 120, showBoundary=1)
            frame.addFromList(Flow_object2, pdf)

            pdf.showPage()

            pdf.drawString(20, 800, "Theory")

            paragraph = []
            styles = getSampleStyleSheet()
            p_text = Paragraph(self.Theory_TextEdit.toPlainText(), style=styles["Normal"])
            paragraph.append(p_text)

            frame = Frame(20, 70, 550, 720, showBoundary=1)
            frame.addFromList(paragraph, pdf)

            pdf.showPage()

            pdf.drawString(20, 800, "Procedure")

            paragraph = []
            styles = getSampleStyleSheet()
            p_text = Paragraph(self.Procedure_TextEdit.toPlainText(), style=styles["Normal"])
            paragraph.append(p_text)

            frame = Frame(20, 70, 550, 720, showBoundary=1)
            frame.addFromList(paragraph, pdf)

            pdf.showPage()

            pdf.drawString(20, 800, "Calculation")

            paragraph = []
            styles = getSampleStyleSheet()
            p_text = Paragraph(self.Calculation_TextEdit.toPlainText(), style=styles["Normal"])
            paragraph.append(p_text)

            frame = Frame(20, 70, 550, 720, showBoundary=1)
            frame.addFromList(paragraph, pdf)

            pdf.showPage()

            pdf.drawString(20, 800, "Results")

            paragraph = []
            styles = getSampleStyleSheet()
            p_text = Paragraph(self.Results_TextEdit.toPlainText(), style=styles["Normal"])
            paragraph.append(p_text)

            frame = Frame(20, 70, 550, 720, showBoundary=1)
            frame.addFromList(paragraph, pdf)

            pdf.showPage()

            pdf.drawString(20, 800, "Discussion and Conclusion")

            paragraph = []
            styles = getSampleStyleSheet()
            p_text = Paragraph(self.Discussion_TextEdit.toPlainText(), style=styles["Normal"])
            paragraph.append(p_text)

            frame = Frame(20, 70, 550, 720, showBoundary=1)
            frame.addFromList(paragraph, pdf)

            pdf.showPage()
            pdf.save()

    def show_front_page(self):

            self.Front_page_label.show(),self.label_12.show(),self.label_13.show(),self.label_14.show()
            self.label_15.show(),self.label_16.show(),self.label_17.show(),self.label_18.show()
            self.label_19.show(),self.lineEdit_26.show(),self.lineEdit_27.show(),self.lineEdit_28.show()
            self.lineEdit_29.show(),self.lineEdit_30.show(),self.lineEdit_31.show()
            self.Front_page_label_2.show(),self.Front_page_label_7.show(), self.Front_page_label_8.show()
            self.label_20.show(),self.lineEdit_33.show(), self.lineEdit_34.hide(), self.Submit_2.hide(), self.lineEdit_32.show()

            self.Equipment_label.hide(), self.Equipment_TextEdit.hide()
            self.label_5.hide(), self.label_7.hide(), self.label_8.hide(), self.label_6.hide(), self.label_9.hide()
            self.label_10.hide(), self.label_11.hide(), self.lineEdit.hide(), self.lineEdit_2.hide(), self.lineEdit_3.hide()
            self.lineEdit_4.hide(), self.lineEdit_5.hide(), self.lineEdit_6.hide(), self.lineEdit_7.hide(), self.lineEdit_8.hide()
            self.lineEdit_9.hide(), self.lineEdit_10.hide(), self.lineEdit_11.hide(), self.lineEdit_12.hide(), self.lineEdit_13.hide()
            self.lineEdit_14.hide(), self.lineEdit_15.hide(), self.lineEdit_16.hide(), self.lineEdit_17.hide(), self.lineEdit_18.hide(), \
            self.lineEdit_19.hide(), self.lineEdit_20.hide(), self.lineEdit_21.hide(), self.lineEdit_22.hide(), self.lineEdit_23.hide(), \
            self.lineEdit_24.hide(), self.lineEdit_25.hide(), self.label_4.hide(), self.label_3.hide()

            self.Theory_label.hide(), self.Theory_TextEdit.hide(), self.Procedure_label.hide(), self.Procedure_TextEdit.hide()
            self.Calculation_label.hide(), self.Calculation_TextEdit.hide(), self.Results_label.hide(), self.Results_TextEdit.hide()
            self.Discussion.hide(), self.Discussion_TextEdit.hide()

    def show_Objective_page(self):

            self.Front_page_label.hide(), self.label_12.hide(), self.label_13.hide()
            self.label_14.hide(), self.label_15.hide(), self.label_16.hide(), self.label_17.hide(),self.label_18.hide()
            self.label_19.hide(), self.lineEdit_26.hide(), self.lineEdit_27.hide(),self.lineEdit_28.hide()
            self.lineEdit_29.hide(), self.lineEdit_30.hide(), self.lineEdit_31.hide()
            self.label_20.hide(), self.lineEdit_33.hide(), self.lineEdit_34.hide(), self.Submit_2.hide()
            self.lineEdit_32.hide()
            self.Front_page_label_2.hide(), self.Front_page_label_7.hide(), self.Front_page_label_8.hide()

            self.Equipment_label.show(), self.Equipment_TextEdit.show()
            self.label_5.show(), self.label_7.show(),  self.label_8.show(), self.label_6.show(), self.label_9.show()
            self.label_10.show(), self.label_11.show(), self.lineEdit.show(), self.lineEdit_2.show(), self.lineEdit_3.show()
            self.lineEdit_4.show(), self.lineEdit_5.show(), self.lineEdit_6.show(), self.lineEdit_7.show(), self.lineEdit_8.show()
            self.lineEdit_9.show(), self.lineEdit_10.show(),self.lineEdit_11.show(), self.lineEdit_12.show(), self.lineEdit_13.show()
            self.lineEdit_14.show(), self.lineEdit_15.show(),self.lineEdit_16.show(), self.lineEdit_17.show(), self.lineEdit_18.show(), \
            self.lineEdit_19.show(), self.lineEdit_20.show(),self.lineEdit_21.show(), self.lineEdit_22.show(), self.lineEdit_23.show(),\
            self.lineEdit_24.show(), self.lineEdit_25.show(),self.label_4.show(),self.lineEdit_32.hide(), self.label_3.show()

            self.Theory_label.hide(),self.Theory_TextEdit.hide(),self.Procedure_label.hide(), self.Procedure_TextEdit.hide()
            self.Calculation_label.hide(),self.Calculation_TextEdit.hide(),self.Results_label.hide(), self.Results_TextEdit.hide()
            self.Discussion.hide(),  self.Discussion_TextEdit.hide()

    def show_Theory_page(self):

            self.Front_page_label.hide(), self.label_12.hide(), self.label_13.hide()
            self.label_14.hide(), self.label_15.hide(), self.label_16.hide(), self.label_17.hide(),self.label_18.hide()
            self.label_19.hide(), self.lineEdit_26.hide(), self.lineEdit_27.hide(),self.lineEdit_28.hide()
            self.lineEdit_29.hide(), self.lineEdit_30.hide(), self.lineEdit_31.hide()
            self.label_20.hide(), self.lineEdit_33.hide(), self.lineEdit_34.hide(), self.Submit_2.hide()
            self.lineEdit_32.hide()
            self.Front_page_label_2.hide(), self.Front_page_label_7.hide(), self.Front_page_label_8.hide()


            self.Equipment_label.hide(), self.Equipment_TextEdit.hide()
            self.label_5.hide(), self.label_7.hide(), self.label_8.hide(), self.label_6.hide(), self.label_9.hide()
            self.label_10.hide(), self.label_11.hide(), self.lineEdit.hide(), self.lineEdit_2.hide(), self.lineEdit_3.hide()
            self.lineEdit_4.hide(), self.lineEdit_5.hide(), self.lineEdit_6.hide(), self.lineEdit_7.hide(), self.lineEdit_8.hide()
            self.lineEdit_9.hide(), self.lineEdit_10.hide(), self.lineEdit_11.hide(), self.lineEdit_12.hide(), self.lineEdit_13.hide()
            self.lineEdit_14.hide(), self.lineEdit_15.hide(), self.lineEdit_16.hide(), self.lineEdit_17.hide(), self.lineEdit_18.hide(), \
            self.lineEdit_19.hide(), self.lineEdit_20.hide(), self.lineEdit_21.hide(), self.lineEdit_22.hide(), self.lineEdit_23.hide(), \
            self.lineEdit_24.hide(), self.lineEdit_25.hide(), self.label_4.hide(), self.label_3.hide(), self.lineEdit_32.hide()

            self.Theory_label.show(),self.Theory_TextEdit.show(),self.Procedure_label.hide(),self.Procedure_TextEdit.hide()
            self.Calculation_label.hide(),self.Calculation_TextEdit.hide(),self.Results_label.hide(),self.Results_TextEdit.hide()
            self.Discussion.hide(),self.Discussion_TextEdit.hide()

    def show_Procedure_page(self):

            self.Front_page_label.hide(), self.label_12.hide(), self.label_13.hide()
            self.label_14.hide(), self.label_15.hide(), self.label_16.hide(), self.label_17.hide(),self.label_18.hide()
            self.label_19.hide(), self.lineEdit_26.hide(), self.lineEdit_27.hide(),self.lineEdit_28.hide()
            self.lineEdit_29.hide(), self.lineEdit_30.hide(), self.lineEdit_31.hide()
            self.label_20.hide(), self.lineEdit_33.hide(), self.lineEdit_34.hide(), self.Submit_2.hide()
            self.lineEdit_32.hide()
            self.Front_page_label_2.hide(), self.Front_page_label_7.hide(), self.Front_page_label_8.hide()


            self.Equipment_label.hide(), self.Equipment_TextEdit.hide()
            self.label_5.hide(), self.label_7.hide(), self.label_8.hide(), self.label_6.hide(), self.label_9.hide()
            self.label_10.hide(), self.label_11.hide(), self.lineEdit.hide(), self.lineEdit_2.hide(), self.lineEdit_3.hide()
            self.lineEdit_4.hide(), self.lineEdit_5.hide(), self.lineEdit_6.hide(), self.lineEdit_7.hide(), self.lineEdit_8.hide()
            self.lineEdit_9.hide(), self.lineEdit_10.hide(), self.lineEdit_11.hide(), self.lineEdit_12.hide(), self.lineEdit_13.hide()
            self.lineEdit_14.hide(), self.lineEdit_15.hide(), self.lineEdit_16.hide(), self.lineEdit_17.hide(), self.lineEdit_18.hide(), \
            self.lineEdit_19.hide(), self.lineEdit_20.hide(), self.lineEdit_21.hide(), self.lineEdit_22.hide(), self.lineEdit_23.hide(), \
            self.lineEdit_24.hide(), self.lineEdit_25.hide(), self.label_4.hide(), self.label_3.hide(), self.lineEdit_32.hide()

            self.Theory_label.hide(),self.Theory_TextEdit.hide(),self.Procedure_label.show()
            self.Procedure_TextEdit.show(),self.Calculation_label.hide(),self.Calculation_TextEdit.hide()
            self.Results_label.hide(),self.Results_TextEdit.hide(),self.Discussion.hide()
            self.Discussion_TextEdit.hide()

    def show_calculation_page(self):

            self.Front_page_label.hide(), self.label_12.hide(), self.label_13.hide()
            self.label_14.hide(), self.label_15.hide(), self.label_16.hide(), self.label_17.hide(),self.label_18.hide()
            self.label_19.hide(), self.lineEdit_26.hide(), self.lineEdit_27.hide(),self.lineEdit_28.hide()
            self.lineEdit_29.hide(), self.lineEdit_30.hide(), self.lineEdit_31.hide()
            self.label_20.hide(), self.lineEdit_33.hide(), self.lineEdit_34.hide(), self.Submit_2.hide()
            self.lineEdit_32.hide()
            self.Front_page_label_2.hide(), self.Front_page_label_7.hide(), self.Front_page_label_8.hide()


            self.Equipment_label.hide(), self.Equipment_TextEdit.hide()
            self.label_5.hide(), self.label_7.hide(), self.label_8.hide(), self.label_6.hide(), self.label_9.hide()
            self.label_10.hide(), self.label_11.hide(), self.lineEdit.hide(), self.lineEdit_2.hide(), self.lineEdit_3.hide()
            self.lineEdit_4.hide(), self.lineEdit_5.hide(), self.lineEdit_6.hide(), self.lineEdit_7.hide(), self.lineEdit_8.hide()
            self.lineEdit_9.hide(), self.lineEdit_10.hide(), self.lineEdit_11.hide(), self.lineEdit_12.hide(), self.lineEdit_13.hide()
            self.lineEdit_14.hide(), self.lineEdit_15.hide(), self.lineEdit_16.hide(), self.lineEdit_17.hide(), self.lineEdit_18.hide(), \
            self.lineEdit_19.hide(), self.lineEdit_20.hide(), self.lineEdit_21.hide(), self.lineEdit_22.hide(), self.lineEdit_23.hide(), \
            self.lineEdit_24.hide(), self.lineEdit_25.hide(), self.label_4.hide(), self.label_3.hide(), self.lineEdit_32.hide()

            self.Theory_label.hide(),self.Theory_TextEdit.hide(),self.Procedure_label.hide(),self.Procedure_TextEdit.hide()
            self.Calculation_label.show(),self.Calculation_TextEdit.show(),self.Results_label.hide()
            self.Results_TextEdit.hide(),self.Discussion.hide(),self.Discussion_TextEdit.hide()

    def show_result_page(self):

            self.Front_page_label.hide(), self.label_12.hide(), self.label_13.hide()
            self.label_14.hide(), self.label_15.hide(), self.label_16.hide(), self.label_17.hide(),self.label_18.hide()
            self.label_19.hide(), self.lineEdit_26.hide(), self.lineEdit_27.hide(),self.lineEdit_28.hide()
            self.lineEdit_29.hide(), self.lineEdit_30.hide(), self.lineEdit_31.hide()
            self.label_20.hide(), self.lineEdit_33.hide(), self.lineEdit_34.hide(), self.Submit_2.hide()
            self.lineEdit_32.hide()
            self.Front_page_label_2.hide(), self.Front_page_label_7.hide(), self.Front_page_label_8.hide()


            self.Equipment_label.hide(), self.Equipment_TextEdit.hide()
            self.label_5.hide(), self.label_7.hide(), self.label_8.hide(), self.label_6.hide(), self.label_9.hide()
            self.label_10.hide(), self.label_11.hide(), self.lineEdit.hide(), self.lineEdit_2.hide(), self.lineEdit_3.hide()
            self.lineEdit_4.hide(), self.lineEdit_5.hide(), self.lineEdit_6.hide(), self.lineEdit_7.hide(), self.lineEdit_8.hide()
            self.lineEdit_9.hide(), self.lineEdit_10.hide(), self.lineEdit_11.hide(), self.lineEdit_12.hide(), self.lineEdit_13.hide()
            self.lineEdit_14.hide(), self.lineEdit_15.hide(), self.lineEdit_16.hide(), self.lineEdit_17.hide(), self.lineEdit_18.hide(), \
            self.lineEdit_19.hide(), self.lineEdit_20.hide(), self.lineEdit_21.hide(), self.lineEdit_22.hide(), self.lineEdit_23.hide(), \
            self.lineEdit_24.hide(), self.lineEdit_25.hide(), self.label_4.hide(), self.label_3.hide(), self.lineEdit_32.hide()

            self.Theory_label.hide(), self.Theory_TextEdit.hide(),self.Procedure_label.hide()
            self.Procedure_TextEdit.hide(),self.Calculation_label.hide(),self.Calculation_TextEdit.hide()
            self.Results_label.show(),self.Results_TextEdit.show(),self.Discussion.hide()
            self.Discussion_TextEdit.hide()

    def show_conclusion_page(self):

            self.Front_page_label.hide(), self.label_12.hide(), self.label_13.hide()
            self.label_14.hide(), self.label_15.hide(), self.label_16.hide(), self.label_17.hide(),self.label_18.hide()
            self.label_19.hide(), self.lineEdit_26.hide(), self.lineEdit_27.hide(),self.lineEdit_28.hide()
            self.lineEdit_29.hide(), self.lineEdit_30.hide(), self.lineEdit_31.hide()
            self.label_20.hide(), self.lineEdit_33.hide(), self.lineEdit_34.show(), self.Submit_2.show()
            self.lineEdit_32.hide()
            self.Front_page_label_2.hide(), self.Front_page_label_7.hide(), self.Front_page_label_8.hide()


            self.Equipment_label.hide(), self.Equipment_TextEdit.hide()
            self.label_5.hide(), self.label_7.hide(), self.label_8.hide(), self.label_6.hide(), self.label_9.hide()
            self.label_10.hide(), self.label_11.hide(), self.lineEdit.hide(), self.lineEdit_2.hide(), self.lineEdit_3.hide()
            self.lineEdit_4.hide(), self.lineEdit_5.hide(), self.lineEdit_6.hide(), self.lineEdit_7.hide(), self.lineEdit_8.hide()
            self.lineEdit_9.hide(), self.lineEdit_10.hide(), self.lineEdit_11.hide(), self.lineEdit_12.hide(), self.lineEdit_13.hide()
            self.lineEdit_14.hide(), self.lineEdit_15.hide(), self.lineEdit_16.hide(), self.lineEdit_17.hide(), self.lineEdit_18.hide(), \
            self.lineEdit_19.hide(), self.lineEdit_20.hide(), self.lineEdit_21.hide(), self.lineEdit_22.hide(), self.lineEdit_23.hide(), \
            self.lineEdit_24.hide(), self.lineEdit_25.hide(), self.label_4.hide(), self.label_3.hide(), self.lineEdit_32.hide()

            self.Theory_label.hide(), self.Theory_TextEdit.hide(),self.Procedure_label.hide()
            self.Procedure_TextEdit.hide(), self.Calculation_label.hide(), self.Calculation_TextEdit.hide()
            self.Results_label.hide(), self.Results_TextEdit.hide(),self.Discussion.show()
            self.Discussion_TextEdit.show()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "     Lab-Report Generator"))
        self.pushButton_FrontPage.setText(_translate("Dialog", "Cover Page"))
        self.pushButton_Objective.setText(_translate("Dialog", "Objective/Equipments"))
        self.pushButton_Theory.setText(_translate("Dialog", "Theory"))
        self.pushButton_Calculation.setText(_translate("Dialog", "Calculation"))
        self.pushButton_Procedure.setText(_translate("Dialog", "Procedure"))
        self.pushButton_Results.setText(_translate("Dialog", "Results"))
        self.pushButton_Conclusion.setText(_translate("Dialog", "Discussion/conclusion"))
        self.Discussion.setText(_translate("Dialog", "  Discussion/Conclusion"))
        self.Submit.setText(_translate("Dialog", "Submit"))
        self.Results_label.setText(_translate("Dialog", "     Results"))
        self.Calculation_label.setText(_translate("Dialog", "  Calculation"))
        self.Procedure_label.setText(_translate("Dialog", "  Procedure"))
        self.Theory_label.setText(_translate("Dialog", "  Theory"))
        self.Equipment_label.setText(_translate("Dialog", " Objective/Equipment"))
        self.label_5.setText(_translate("Dialog", "  Equipment_used"))
        self.label_6.setText(_translate("Dialog", "  Component_used"))
        self.label_7.setText(_translate("Dialog", "Description"))
        self.label_8.setText(_translate("Dialog", "Quantity"))
        self.label_9.setText(_translate("Dialog", "Quantity"))
        self.label_10.setText(_translate("Dialog", "Type"))
        self.label_11.setText(_translate("Dialog", "Description"))
        self.Front_page_label.setText(_translate("Dialog", " Cover Page"))
        self.label_13.setText(_translate("Dialog", "Course No:"))
        self.label_14.setText(_translate("Dialog", "Group No:"))
        self.label_15.setText(_translate("Dialog", "Experiment No:"))
        self.label_16.setText(_translate("Dialog", "Done By:"))
        self.label_17.setText(_translate("Dialog", "Date of Experiment:"))
        self.label_18.setText(_translate("Dialog", "Date of Submission:"))
        self.label_19.setText(_translate("Dialog", "Title:"))
        self.lineEdit_26.setPlaceholderText(_translate("Dialog", "Your Answer"))
        self.lineEdit_27.setPlaceholderText(_translate("Dialog", "Your Answer"))
        self.lineEdit_28.setPlaceholderText(_translate("Dialog", "Your Answer"))
        self.lineEdit_29.setPlaceholderText(_translate("Dialog", "Your Answer"))
        self.lineEdit_30.setPlaceholderText(_translate("Dialog", "Your Answer"))
        self.lineEdit_31.setPlaceholderText(_translate("Dialog", "Your Answer"))
        self.lineEdit_32.setPlaceholderText(_translate("Dialog", "Your Answer"))
        self.label_20.setText(_translate("Dialog", "ID No."))
        self.lineEdit_33.setPlaceholderText(_translate("Dialog", "Your Answer"))
        self.Submit_2.setText(_translate("Dialog", "Save"))
        self.lineEdit_34.setPlaceholderText(_translate("Dialog", "  Enter File Name"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
