# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Experiment_1 import *
from Multi_Band_Resistor_Color_Code_Calculator import *
from  Experiment_1_Wired import *
from  Experiment_3_PART_A_test1 import *
from  Experiment_3_PART_B1_1 import *
from Experiment_5_Test2 import *
from Experiment_6_Test2 import *
from Star_Delta_Circuit2 import *
from Bridge_circuit_Test3 import *
from  Modulation_and_Demodulation import *
from  LabReportpdfgenerator2 import *
from  Experiments_Lab_Manual import *
class my_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1365, 817)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 100, 251, 591))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    background-color: rgb(240, 240, 240);\n"
"border: 5px solid;\n"
" \n"
"    border-top-color: rgb(240, 240, 240);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-left-color: rgb(255, 255, 255);\n"
"    border-right-color: rgb(79, 58, 80);\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.checkBox_Fundamental_Circuit = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Fundamental_Circuit.setGeometry(QtCore.QRect(20, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_Fundamental_Circuit.setFont(font)
        self.checkBox_Fundamental_Circuit.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.checkBox_Fundamental_Circuit.setObjectName("checkBox_Fundamental_Circuit")
        self.checkBox_Resistor_Color_Code = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Resistor_Color_Code.setGeometry(QtCore.QRect(50, 70, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_Resistor_Color_Code.setFont(font)
        self.checkBox_Resistor_Color_Code.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"")
        self.checkBox_Resistor_Color_Code.setObjectName("checkBox_Resistor_Color_Code")
        self.checkBox_Experiment_1 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Experiment_1.setGeometry(QtCore.QRect(50, 120, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_Experiment_1.setFont(font)
        self.checkBox_Experiment_1.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.checkBox_Experiment_1.setObjectName("checkBox_Experiment_1")
        self.checkBox_Experiment_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Experiment_2.setGeometry(QtCore.QRect(50, 160, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_Experiment_2.setFont(font)
        self.checkBox_Experiment_2.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.checkBox_Experiment_2.setObjectName("checkBox_Experiment_2")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setGeometry(QtCore.QRect(50, 200, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.checkBox_5.setObjectName("checkBox_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 90, 1061, 621))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"border:none;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 55, 191, 258))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"border:1px solid black;\n"
"border-radius: 15px;\n"
"    border-color: rgb(79, 58, 80);\n"
"}")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 175, 4))
        self.label_4.setStyleSheet("QLabel{\n"
"    background-color: rgb(79, 58, 80);\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_Resistor_Color_code = QtWidgets.QLabel(self.groupBox_2)
        self.label_Resistor_Color_code.setGeometry(QtCore.QRect(12, 139, 181, 171))
        self.label_Resistor_Color_code.setStyleSheet("QLabel{\n"
"border-radius:15px 15px 15px 15px;\n"
"}\n"
"")
        self.label_Resistor_Color_code.setText("")
        self.label_Resistor_Color_code.setPixmap(QtGui.QPixmap("resistor-res5.gif"))
        self.label_Resistor_Color_code.setScaledContents(True)
        self.label_Resistor_Color_code.setObjectName("label_Resistor_Color_code")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(230, 55, 191, 258))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel{\n"
"border:1px solid black;\n"
"border-radius: 15px;\n"
"    border-color: rgb(79, 58, 80);\n"
"}")
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(240, 120, 175, 4))
        self.label_17.setStyleSheet("QLabel{\n"
"    background-color: rgb(79, 58, 80);\n"
"}")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(240, 145, 171, 151))
        self.label_6.setStyleSheet("QLabel{\n"
"border-radius:15px 15px 15px 15px;\n"
"}\n"
"QLabel:hover{\n"
"    background-color: rgb(132, 97, 85);\n"
"}\n"
"")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("multimeter_current.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(450, 140, 191, 171))
        self.label_8.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QLabel:hover{\n"
"    background-color: rgba(51, 51, 51,0.5);\n"
"border-radius: 15px;\n"
"}")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(440, 55, 191, 258))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel{\n"
"border:1px solid black;\n"
"border-radius: 15px;\n"
"    border-color: rgb(79, 58, 80);\n"
"}")
        self.label_16.setTextFormat(QtCore.Qt.AutoText)
        self.label_16.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(450, 120, 175, 4))
        self.label_18.setStyleSheet("QLabel{\n"
"    background-color: rgb(79, 58, 80);\n"
"}")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(450, 150, 171, 151))
        self.label_9.setStyleSheet("QLabel{\n"
"border-radius:15px 15px 15px 15px;\n"
"}\n"
"QLabel:hover{\n"
"    background-color: rgb(132, 97, 85);\n"
"}\n"
"")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("multimeter_current.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(655, 55, 191, 258))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("QLabel{\n"
"border:1px solid black;\n"
"border-radius: 15px;\n"
"    border-color: rgb(79, 58, 80);\n"
"}")
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_20.setObjectName("label_20")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(665, 120, 175, 4))
        self.label_19.setStyleSheet("QLabel{\n"
"    background-color: rgb(79, 58, 80);\n"
"}")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(660, 145, 181, 161))
        self.label_11.setStyleSheet("QLabel{\n"
"border-radius:25px;\n"
"}")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("KCL KVL 1.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.pushButton_Experiment_1 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Experiment_1.setGeometry(QtCore.QRect(230, 141, 191, 171))
        self.pushButton_Experiment_1.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(51, 51, 51,0.5);\n"
"border-radius: 15px;\n"
"}")
        self.pushButton_Experiment_1.setText("")
        self.pushButton_Experiment_1.setObjectName("pushButton_Experiment_1")
        self.pushButton_Experiment_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Experiment_2.setGeometry(QtCore.QRect(440, 141, 191, 171))
        self.pushButton_Experiment_2.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(51, 51, 51,0.5);\n"
"border-radius: 15px;\n"
"}")
        self.pushButton_Experiment_2.setText("")
        self.pushButton_Experiment_2.setObjectName("pushButton_Experiment_2")
        self.pushButton_KVL_KCL = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_KVL_KCL.setGeometry(QtCore.QRect(655, 141, 191, 171))
        self.pushButton_KVL_KCL.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(51, 51, 51,0.5);\n"
"border-radius: 15px;\n"
"}")
        self.pushButton_KVL_KCL.setText("")
        self.pushButton_KVL_KCL.setObjectName("pushButton_KVL_KCL")
        self.pushButton_Resistor__Color_Code = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Resistor__Color_Code.setGeometry(QtCore.QRect(10, 132, 191, 180))
        self.pushButton_Resistor__Color_Code.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(51, 51, 51,0.5);\n"
"border-radius: 15px;\n"
"pushbutton.setToolTip( \"Click this button to open file\"  );\n"
"}")
        self.pushButton_Resistor__Color_Code.setText("")
        self.pushButton_Resistor__Color_Code.setObjectName("pushButton_Resistor__Color_Code")
        self.pushButton_Periodic_wavegenerator = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Periodic_wavegenerator.setGeometry(QtCore.QRect(870, 131, 191, 181))
        self.pushButton_Periodic_wavegenerator.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(51, 51, 51,0.5);\n"
"border-radius: 15px;\n"
"}")
        self.pushButton_Periodic_wavegenerator.setText("")
        self.pushButton_Periodic_wavegenerator.setObjectName("pushButton_Periodic_wavegenerator")
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(870, 55, 191, 258))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("QLabel{\n"
"border:1px solid black;\n"
"border-radius: 15px;\n"
"    border-color: rgb(79, 58, 80);\n"
"}")
        self.label_30.setTextFormat(QtCore.Qt.AutoText)
        self.label_30.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_30.setObjectName("label_30")
        self.label_29 = QtWidgets.QLabel(self.groupBox_2)
        self.label_29.setGeometry(QtCore.QRect(880, 120, 175, 4))
        self.label_29.setStyleSheet("QLabel{\n"
"    background-color: rgb(79, 58, 80);\n"
"}")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(875, 140, 181, 161))
        self.label_14.setStyleSheet("QLabel{\n"
"border-radius:25px;\n"
"}")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("Periodic_wave.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(10, 330, 191, 261))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("QLabel{\n"
"border:1px solid black;\n"
"border-radius: 15px;\n"
"    border-color: rgb(79, 58, 80);\n"
"}")
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_21.setObjectName("label_21")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(20, 390, 175, 4))
        self.label_25.setStyleSheet("QLabel{\n"
"    background-color: rgb(79, 58, 80);\n"
"}")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 430, 171, 151))
        self.label_7.setStyleSheet("QLabel{\n"
"border-radius:15px 15px 15px 15px;\n"
"}\n"
"QLabel:hover{\n"
"    background-color: rgb(132, 97, 85);\n"
"}\n"
"")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("transient.PNG"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.pushButton_Transient = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Transient.setGeometry(QtCore.QRect(10, 420, 191, 172))
        self.pushButton_Transient.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(51, 51, 51,0.5);\n"
"border-radius: 15px;\n"
"}")
        self.pushButton_Transient.setText("")
        self.pushButton_Transient.setObjectName("pushButton_Transient")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(230, 330, 191, 258))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("QLabel{\n"
"border:1px solid black;\n"
"border-radius: 15px;\n"
"    border-color: rgb(79, 58, 80);\n"
"}")
        self.label_22.setTextFormat(QtCore.Qt.AutoText)
        self.label_22.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_22.setObjectName("label_22")
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        self.label_26.setGeometry(QtCore.QRect(240, 390, 175, 4))
        self.label_26.setStyleSheet("QLabel{\n"
"    background-color: rgb(79, 58, 80);\n"
"}")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(240, 440, 171, 141))
        self.label_10.setStyleSheet("QLabel{\n"
"border-radius:15px 15px 15px 15px;\n"
"}\n"
"QLabel:hover{\n"
"    background-color: rgb(132, 97, 85);\n"
"}\n"
"")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("Star_Delta_Icon.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.pushButton_Star_Delta = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Star_Delta.setGeometry(QtCore.QRect(230, 424, 191, 163))
        self.pushButton_Star_Delta.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(51, 51, 51,0.5);\n"
"border-radius: 15px;\n"
"}")
        self.pushButton_Star_Delta.setText("")
        self.pushButton_Star_Delta.setObjectName("pushButton_Star_Delta")
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(440, 330, 191, 258))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("QLabel{\n"
"border:1px solid black;\n"
"border-radius: 15px;\n"
"    border-color: rgb(79, 58, 80);\n"
"}")
        self.label_23.setTextFormat(QtCore.Qt.AutoText)
        self.label_23.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_23.setObjectName("label_23")
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setGeometry(QtCore.QRect(450, 400, 175, 4))
        self.label_27.setStyleSheet("QLabel{\n"
"    background-color: rgb(79, 58, 80);\n"
"}")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(450, 420, 171, 151))
        self.label_12.setStyleSheet("QLabel{\n"
"border-radius:15px 15px 15px 15px;\n"
"}\n"
"QLabel:hover{\n"
"    background-color: rgb(132, 97, 85);\n"
"}\n"
"")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("Wheatstone_ Bridge.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.pushButton_Bridge = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Bridge.setGeometry(QtCore.QRect(440, 419, 191, 171))
        self.pushButton_Bridge.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(51, 51, 51,0.5);\n"
"border-radius: 15px;\n"
"}")
        self.pushButton_Bridge.setText("")
        self.pushButton_Bridge.setObjectName("pushButton_Bridge")
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(655, 330, 191, 261))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("QLabel{\n"
"border:1px solid black;\n"
"border-radius: 15px;\n"
"    border-color: rgb(79, 58, 80);\n"
"}")
        self.label_24.setTextFormat(QtCore.Qt.AutoText)
        self.label_24.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_24.setObjectName("label_24")
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setGeometry(QtCore.QRect(660, 400, 175, 4))
        self.label_28.setStyleSheet("QLabel{\n"
"    background-color: rgb(79, 58, 80);\n"
"}")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(665, 440, 171, 141))
        self.label_13.setStyleSheet("QLabel{\n"
"border-radius:15px 15px 15px 15px;\n"
"}\n"
"QLabel:hover{\n"
"    background-color: rgb(132, 97, 85);\n"
"}\n"
"")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("Mod_Demod.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.pushButton_Mod_Demod = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Mod_Demod.setGeometry(QtCore.QRect(655, 420, 191, 171))
        self.pushButton_Mod_Demod.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(51, 51, 51,0.5);\n"
"border-radius: 15px;\n"
"}")
        self.pushButton_Mod_Demod.setText("")
        self.pushButton_Mod_Demod.setObjectName("pushButton_Mod_Demod")
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_Resistor_Color_code.raise_()
        self.label_15.raise_()
        self.label_17.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.label_16.raise_()
        self.label_18.raise_()
        self.label_9.raise_()
        self.label_20.raise_()
        self.label_19.raise_()
        self.label_11.raise_()
        self.pushButton_Experiment_1.raise_()
        self.pushButton_Experiment_2.raise_()
        self.pushButton_KVL_KCL.raise_()
        self.pushButton_Resistor__Color_Code.raise_()
        self.label_30.raise_()
        self.label_29.raise_()
        self.label_14.raise_()
        self.pushButton_Periodic_wavegenerator.raise_()
        self.label_21.raise_()
        self.label_25.raise_()
        self.label_7.raise_()
        self.pushButton_Transient.raise_()
        self.label_22.raise_()
        self.label_26.raise_()
        self.label_10.raise_()
        self.pushButton_Star_Delta.raise_()
        self.label_23.raise_()
        self.label_27.raise_()
        self.label_12.raise_()
        self.pushButton_Bridge.raise_()
        self.label_24.raise_()
        self.label_28.raise_()
        self.label_13.raise_()
        self.pushButton_Mod_Demod.raise_()
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(19, 36, 1325, 5))
        self.label.setStyleSheet("QLabel{\n"
"    background-color: rgb(79, 58, 80);\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_Lab_manual = QtWidgets.QLabel(self.centralwidget)
        self.label_Lab_manual.setGeometry(QtCore.QRect(1300, 50, 41, 41))
        self.label_Lab_manual.setText("")
        self.label_Lab_manual.setPixmap(QtGui.QPixmap("user_manual.jpg"))
        self.label_Lab_manual.setScaledContents(True)
        self.label_Lab_manual.setObjectName("label_Lab_manual")
        self.label_Lab_report = QtWidgets.QLabel(self.centralwidget)
        self.label_Lab_report.setGeometry(QtCore.QRect(1230, 48, 43, 43))
        self.label_Lab_report.setText("")
        self.label_Lab_report.setPixmap(QtGui.QPixmap("lab_report.jpeg"))
        self.label_Lab_report.setScaledContents(True)
        self.label_Lab_report.setObjectName("label_Lab_report")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1501, 771))
        self.label_3.setStyleSheet("QLabel{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton_lab_manual = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_lab_manual.setGeometry(QtCore.QRect(1295, 43, 52, 52))
        self.pushButton_lab_manual.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(51, 51, 51,0.1);\n"
"   border-radius: 15px;    \n"
"}")
        self.pushButton_lab_manual.setText("")
        self.pushButton_lab_manual.setObjectName("pushButton_lab_manual")
        self.pushButton_lab_report = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_lab_report.setGeometry(QtCore.QRect(1227, 43, 52, 52))
        self.pushButton_lab_report.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(51, 51, 51,0.1);\n"
"   border-radius: 15px;    \n"
"}")
        self.pushButton_lab_report.setText("")
        self.pushButton_lab_report.setObjectName("pushButton_lab_report")
        self.label_3.raise_()
        self.groupBox.raise_()
        self.label.raise_()
        self.groupBox_2.raise_()
        self.label_Lab_manual.raise_()
        self.label_Lab_report.raise_()
        self.pushButton_lab_manual.raise_()
        self.pushButton_lab_report.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton_Resistor__Color_Code.clicked.connect(self.resistor_color_code)
        self.pushButton_Experiment_1.clicked.connect(self.experiment_one)
        self.pushButton_Experiment_2.clicked.connect(self.experiment_two)
        self.pushButton_KVL_KCL.clicked.connect(self.kVL_KCL)
        self.pushButton_Periodic_wavegenerator.clicked.connect(self.wave_generation)
        self.pushButton_Transient.clicked.connect(self.transient)
        self.pushButton_Star_Delta.clicked.connect(self.star_Delta)
        self.pushButton_Bridge.clicked.connect(self.bridge)
        self.pushButton_Mod_Demod.clicked.connect(self.mod_Demod)

        self.pushButton_lab_report.clicked.connect(self.labreport)
        self.pushButton_lab_manual.clicked.connect(self.labmanual)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def resistor_color_code(self):
            self.colorcode_window = QtWidgets.QMainWindow()
            self.Resis_ui = Resistor_MainWindow()
            self.Resis_ui.setupUi(self.colorcode_window)
            self.colorcode_window.show()
            # Ui_Dialog.dis_player()

    def experiment_one(self):
            self.colorcode_window = QtWidgets.QMainWindow()
            self.Resis_ui = Experiment_one_MainWindow()
            self.Resis_ui.setupUi(self.colorcode_window)
            self.colorcode_window.show()

    def experiment_two(self):
            self.colorcode_window = QtWidgets.QMainWindow()
            self.Resis_ui = Experiment_two_MainWindow()
            self.Resis_ui.setupUi(self.colorcode_window)
            self.colorcode_window.show()
    def kVL_KCL(self):
            self.colorcode_window = QtWidgets.QMainWindow()
            self.Resis_ui =  kvl_MainWindow()
            self.Resis_ui.setupUi(self.colorcode_window)
            self.colorcode_window.show()

    def wave_generation(self):
            self.colorcode_window = QtWidgets.QMainWindow()
            self.Resis_ui =   Experiment_5_MainWindow()
            self.Resis_ui.setupUi(self.colorcode_window)
            self.colorcode_window.show()

    def transient(self):
            self.colorcode_window = QtWidgets.QMainWindow()
            self.Resis_ui = Experiment_6_MainWindow()
            self.Resis_ui.setupUi(self.colorcode_window)
            self.colorcode_window.show()

    def star_Delta(self):
            self.colorcode_window = QtWidgets.QMainWindow()
            self.Resis_ui =  star_delta_MainWindow()
            self.Resis_ui.setupUi(self.colorcode_window)
            self.colorcode_window.show()

    def bridge(self):
            self.colorcode_window = QtWidgets.QMainWindow()
            self.Resis_ui = Bridge_MainWindow()
            self.Resis_ui.setupUi(self.colorcode_window)
            self.colorcode_window.show()

    def mod_Demod(self):
            self.colorcode_window = QtWidgets.QMainWindow()
            self.Resis_ui =  Modem_MainWindow()
            self.Resis_ui.setupUi(self.colorcode_window)
            self.colorcode_window.show()

    def labreport(self):
            dialg = QtWidgets.QDialog()
            dialg.ui = Ui_Dialog()
            dialg.ui.setupUi(dialg)
            dialg.exec_()
            dialg.show()
    def labmanual(self):
            self.colorcode_window = QtWidgets.QMainWindow()
            self.Resis_ui =  Lab_MainWindow()
            self.Resis_ui.setupUi(self.colorcode_window)
            self.colorcode_window.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lab Experiments"))
        self.groupBox.setTitle(_translate("MainWindow", "Courses"))
        self.checkBox_Fundamental_Circuit.setText(_translate("MainWindow", "Fundamental of Circuit"))
        self.checkBox_Resistor_Color_Code.setText(_translate("MainWindow", "Resistor Color Code"))
        self.checkBox_Experiment_1.setText(_translate("MainWindow", "Experiment-1"))
        self.checkBox_Experiment_2.setText(_translate("MainWindow", "Experiment-2"))
        self.checkBox_5.setText(_translate("MainWindow", "Experiment-3"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Fundamentals of Circuit Lab Experiments"))
        self.label_2.setText(_translate("MainWindow", "Resistor Color Code\n"
"Calculator"))
        self.label_15.setText(_translate("MainWindow", "Experiment 1: Measurem-\n"
"ent of D.C. Currents,\n"
"Voltage, Resistances Part 1"))
        self.label_16.setText(_translate("MainWindow", "Experiment 2: Measurem-\n"
"ent of D.C. Currents,\n"
"Voltage, Resistances Part 2"))
        self.label_20.setText(_translate("MainWindow", "Experiment 3: KVL, KCL,\n"
"Thevenin\'s Theorem\n"
"and Norton\'s Theorem"))
        self.label_30.setText(_translate("MainWindow", "Experiment 4: Periodic \n"
"Wave Form and \n"
"Measurment"))
        self.label_21.setText(_translate("MainWindow", "\n"
"Transient Analysis: RC \n"
"and R-L Circuits"))
        self.label_22.setText(_translate("MainWindow", "Star Network Connected \n"
"in Parallel with Delta\n"
"Circuit"))
        self.label_23.setText(_translate("MainWindow", "\n"
"Wheatstone Bridge \n"
"Circuit"))
        self.label_24.setText(_translate("MainWindow", "Amplitude and Frequency \n"
" Modulator and \n"
"Demodulator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = my_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
