# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Multi_Band_Resistor_Color_Code_Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Color_Mapper
import Tolerance_Maping
import  Temperature_Coefficient_Mapping
from  Experiments_Lab_Manual import *

class Resistor_MainWindow(object):

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1371, 705)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    \n"
"    background-color: rgb(234, 234, 234);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-90, -10, 1500, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(50, 75, 97);\n"
"    color: White;\n"
"}")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 70, 491, 491))
        self.label_3.setStyleSheet("QLabel{    \n"
"    \n"
"    background-color: rgb(187, 218, 252);\n"
"border-radius:40px;\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(800, 70, 481, 491))
        self.label_4.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(187, 218, 252);\n"
"border-radius:40px;\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(440, 80, 60, 60))
        self.label_5.setStyleSheet("QLabel\n"
"{\n"
"    \n"
"    background-color: rgb(201, 174, 136);\n"
"border-radius:30px;\n"
"}")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(310, 90, 151, 41))
        self.label_7.setStyleSheet("QLabel{\n"
"background-color: rgb(201, 174, 136);\n"
"border-radius:10px;\n"
"}")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(500, 110, 81, 5))
        self.label_8.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:2px;\n"
"}")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(270, 80, 60, 60))
        self.label_13.setStyleSheet("QLabel\n"
"{\n"
"    \n"
"    background-color: rgb(201, 174, 136);\n"
"border-radius:30px;\n"
"}")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(190, 110, 81, 5))
        self.label_9.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:2px;\n"
"}")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(293, 80, 12, 60))
        self.label_6.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 0, 0);\n"
"border-radius:2px;\n"
"}")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(340, 90, 12, 41))
        self.label_10.setStyleSheet("background-color: blue;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(365, 90, 12, 41))
        self.label_11.setStyleSheet("background-color: black;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(390, 90, 12, 41))
        self.label_12.setStyleSheet("background-color: brown;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(930, 100, 60, 60))
        self.label_15.setStyleSheet("QLabel\n"
"{\n"
"    \n"
"    background-color: rgb(201, 174, 136);\n"
"border-radius:30px;\n"
"}")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(1100, 100, 60, 60))
        self.label_16.setStyleSheet("QLabel\n"
"{\n"
"    \n"
"    background-color: rgb(201, 174, 136);\n"
"border-radius:30px;\n"
"}")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(970, 110, 151, 41))
        self.label_17.setStyleSheet("QLabel\n"
"{\n"
"    \n"
"    background-color: rgb(201, 174, 136);\n"
"border-radius:30px;\n"
"}")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(953, 100, 12, 60))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_18.setStyleSheet("QLabel{\n"
                                    "background-color: rgb(255, 0, 0);\n"
                                    "border-radius:2px;\n"
                                    "}")

        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(990, 110, 12, 41))
        self.label_19.setStyleSheet("background-color: blue;")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(1020, 110, 12, 41))
        self.label_20.setStyleSheet("background-color: black;")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(1050, 110, 12, 41))
        self.label_21.setStyleSheet("background-color: brown;")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(1160, 130, 50, 5))
        self.label_23.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:2px;\n"
"}")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(880, 130, 50, 5))
        self.label_24.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:2px;\n"
"}")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.First_combox = QtWidgets.QComboBox(self.centralwidget)
        self.First_combox.setGeometry(QtCore.QRect(160, 190, 69, 22))
        self.First_combox.setStyleSheet("QComboBox\n"
"{\n"
"border:none;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.First_combox.setObjectName("First_combox")
        self.First_combox.addItem("")
        self.First_combox.addItem("")
        self.First_combox.addItem("")
        self.First_combox.addItem("")
        self.First_combox.addItem("")
        self.First_combox.addItem("")
        self.First_combox.addItem("")
        self.First_combox.addItem("")
        self.First_combox.addItem("")
        self.First_combox.addItem("")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(160, 160, 71, 21))
        self.label_25.setStyleSheet("QLabel{\n"
"    background-color: rgb(187, 218, 252);\n"
"color:black;\n"
"\n"
"}")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(400, 160, 71, 21))
        self.label_26.setStyleSheet("QLabel{\n"
"    background-color: rgb(187, 218, 252);\n"
"color:black;\n"
"\n"
"}")
        self.label_26.setObjectName("label_26")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(320, 160, 71, 21))
        self.label_28.setStyleSheet("QLabel{\n"
"    background-color: rgb(187, 218, 252);\n"
"color:black;\n"
"\n"
"}")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(240, 160, 71, 21))
        self.label_29.setStyleSheet("QLabel{\n"
"    background-color: rgb(187, 218, 252);\n"
"color:black;\n"
"\n"
"}")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(160, 230, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(184, 215, 248);\n"
"color:black;\n"
"\n"
"}")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(200, 290, 371, 181))
        self.label_31.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: white;\n"
"   color:White;\n"
"border-radius:20px;\n"
"\n"
"}")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.pushButton_Band_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Band_4.setGeometry(QtCore.QRect(10, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Band_4.setFont(font)
        self.pushButton_Band_4.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"opacity:0.7;\n"
"color:Black;\n"
"border:2px solid rgb(127, 110, 87);;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(51, 51, 51, 0.5);\n"
"}\n"
"")
        self.pushButton_Band_4.setObjectName("pushButton_Band_4")
        self.pushButton_Band_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Band_5.setGeometry(QtCore.QRect(10, 190, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Band_5.setFont(font)
        self.pushButton_Band_5.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"opacity:0.7;\n"
"color:Black;\n"
"border:2px solid rgb(127, 110, 87);;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(51, 51, 51, 0.5);\n"
"}\n"
"")
        self.pushButton_Band_5.setObjectName("pushButton_Band_5")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(210, 300, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("QLabel\n"
"{\n"
"    background-color: white;\n"
"    color:black;\n"
"}")
        self.label_32.setObjectName("label_32")
        self.Rsistor_value = QtWidgets.QLabel(self.centralwidget)
        self.Rsistor_value.setGeometry(QtCore.QRect(350, 300, 81, 31))
        self.Rsistor_value.setStyleSheet("QLabel\n"
"{\n"
"    background-color: White;\n"
"    color:black;\n"
"}")
        self.Rsistor_value.setObjectName("Rsistor_value")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(420, 300, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("QLabel\n"
"{\n"
"    background-color: white;\n"
"color:black;\n"
"}")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(210, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("QLabel\n"
"{\n"
"    background-color: white;\n"
"    color:black;\n"
"}")
        self.label_35.setObjectName("label_35")
        self.Tolerance_value = QtWidgets.QLabel(self.centralwidget)
        self.Tolerance_value.setGeometry(QtCore.QRect(350, 340, 81, 31))
        self.Tolerance_value.setStyleSheet("QLabel\n"
"{\n"
"    background-color: White;\n"
"    color:black;\n"
"}")
        self.Tolerance_value.setObjectName("Tolerance_value")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(210, 380, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("QLabel\n"
"{\n"
"    background-color: white;\n"
"    color:black;\n"
"}")
        self.label_38.setObjectName("label_38")
        self.Minimum_value = QtWidgets.QLabel(self.centralwidget)
        self.Minimum_value.setGeometry(QtCore.QRect(350, 380, 81, 31))
        self.Minimum_value.setStyleSheet("QLabel\n"
"{\n"
"    background-color: White;\n"
"    color:black;\n"
"}")
        self.Minimum_value.setObjectName("Minimum_value")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(210, 420, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("QLabel\n"
"{\n"
"    background-color: white;\n"
"    color:black;\n"
"}")
        self.label_41.setObjectName("label_41")
        self.Maximum_value = QtWidgets.QLabel(self.centralwidget)
        self.Maximum_value.setGeometry(QtCore.QRect(350, 420, 71, 31))
        self.Maximum_value.setStyleSheet("QLabel\n"
"{\n"
"    background-color: White;\n"
"    color:black;\n"
"}")
        self.Maximum_value.setObjectName("Maximum_value")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(420, 380, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("QLabel\n"
"{\n"
"    background-color: white;\n"
"color:black;\n"
"}")
        self.label_37.setObjectName("label_37")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(420, 420, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("QLabel\n"
"{\n"
"    background-color: white;\n"
"color:black;\n"
"}")
        self.label_40.setObjectName("label_40")
        self.pushButton_First_Calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_First_Calculate.setGeometry(QtCore.QRect(330, 490, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_First_Calculate.setFont(font)
        self.pushButton_First_Calculate.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(204, 204, 204);\n"
"opacity:0.7;\n"
"color:Black;\n"
"border:2px solid rgb(127, 110, 87);;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(51, 51, 51, 0.5);\n"
"}\n"
"")
        self.pushButton_First_Calculate.setObjectName("pushButton_First_Calculate")
        self.Second_Resistor_Value = QtWidgets.QLineEdit(self.centralwidget)
        self.Second_Resistor_Value.setGeometry(QtCore.QRect(810, 230, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Second_Resistor_Value.setFont(font)
        self.Second_Resistor_Value.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"text-align:center;\n"
"\n"
"}")
        self.Second_Resistor_Value.setObjectName("Second_Resistor_Value")
        self.Second_Resistor_Tolerance = QtWidgets.QLineEdit(self.centralwidget)
        self.Second_Resistor_Tolerance.setGeometry(QtCore.QRect(1150, 230, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Second_Resistor_Tolerance.setFont(font)
        self.Second_Resistor_Tolerance.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"text-align:center;\n"
"\n"
"}")
        self.Second_Resistor_Tolerance.setObjectName("Second_Resistor_Tolerance")
        self.pushButton_Second_Calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Second_Calculate.setGeometry(QtCore.QRect(990, 470, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Second_Calculate.setFont(font)
        self.pushButton_Second_Calculate.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(204, 204, 204);\n"
"opacity:0.7;\n"
"color:Black;\n"
"border:2px solid rgb(127, 110, 87);;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(51, 51, 51, 0.5);\n"
"}\n"
"")
        self.pushButton_Second_Calculate.setObjectName("pushButton_Second_Calculate")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(900, 350, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("QLabel\n"
"{\n"
"    \n"
"    background-color: rgb(184, 215, 248);\n"
"    color:black;\n"
"}")
        self.label_43.setObjectName("label_43")
        self.Truncated_value = QtWidgets.QLabel(self.centralwidget)
        self.Truncated_value.setGeometry(QtCore.QRect(1060, 350, 171, 41))
        self.Truncated_value.setStyleSheet("QLabel\n"
"{\n"
"    background-color: White;\n"
"    color:black;\n"
"}")
        self.Truncated_value.setObjectName("Truncated_value")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(900, 380, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("QLabel\n"
"{\n"
"    \n"
"    background-color: rgb(187, 218, 252);\n"
"    color:black;\n"
"}")
        self.label_45.setObjectName("label_45")
        self.pushButton_Home = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Home.setGeometry(QtCore.QRect(690, 650, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Home.setFont(font)
        self.pushButton_Home.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(51, 51, 51, 0);\n"
"color:white;\n"
"border:none;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(51, 51, 51, 0.3);\n"
"}\n"
"\n"
"")
        self.pushButton_Home.setText("")
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(710, 100, 5, 421))
        self.label_47.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(127, 110, 87);\n"
"}")
        self.label_47.setText("")
        self.label_47.setObjectName("label_47")
        self.Second_combox = QtWidgets.QComboBox(self.centralwidget)
        self.Second_combox.setGeometry(QtCore.QRect(240, 190, 69, 22))
        self.Second_combox.setStyleSheet("QComboBox\n"
"{\n"
"border:none;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.Second_combox.setObjectName("Second_combox")
        self.Second_combox.addItem("")
        self.Second_combox.addItem("")
        self.Second_combox.addItem("")
        self.Second_combox.addItem("")
        self.Second_combox.addItem("")
        self.Second_combox.addItem("")
        self.Second_combox.addItem("")
        self.Second_combox.addItem("")
        self.Second_combox.addItem("")
        self.Second_combox.addItem("")
        self.Third_combox = QtWidgets.QComboBox(self.centralwidget)
        self.Third_combox.setGeometry(QtCore.QRect(320, 190, 69, 22))
        self.Third_combox.setStyleSheet("QComboBox\n"
"{\n"
"border:none;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.Third_combox.setObjectName("Third_combox")
        self.Third_combox.addItem("")
        self.Third_combox.addItem("")
        self.Third_combox.addItem("")
        self.Third_combox.addItem("")
        self.Third_combox.addItem("")
        self.Third_combox.addItem("")
        self.Third_combox.addItem("")
        self.Third_combox.addItem("")
        self.Third_combox.addItem("")
        self.Third_combox.addItem("")
        self.Fourth_combox = QtWidgets.QComboBox(self.centralwidget)
        self.Fourth_combox.setGeometry(QtCore.QRect(400, 190, 69, 22))
        self.Fourth_combox.setStyleSheet("QComboBox\n"
"{\n"
"border:none;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.Fourth_combox.setObjectName("Fourth_combox")
        self.Fourth_combox.addItem("")
        self.Fourth_combox.addItem("")
        self.Fourth_combox.addItem("")
        self.Fourth_combox.addItem("")
        self.Fourth_combox.addItem("")
        self.Fourth_combox.addItem("")
        self.Fourth_combox.addItem("")
        self.Fourth_combox.addItem("")
        self.Fourth_combox.addItem("")
        self.Fourth_combox.addItem("")
        self.Fourth_combox.addItem("")
        self.Fourth_combox.addItem("")
        self.pushButton_Lab_Manual = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Lab_Manual.setGeometry(QtCore.QRect(1230, 0, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Lab_Manual.setFont(font)
        self.pushButton_Lab_Manual.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Lab_Manual.setStyleSheet("QPushButton\n"
"{\n"
"border:none;\n"
"color:white;\n"
"    background-color: rgb(127, 110, 87);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(51, 51, 51, 0.5);\n"
"}")
        self.pushButton_Lab_Manual.setObjectName("pushButton_Lab_Manual")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 110, 3, 191))
        self.label_2.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(127, 110, 87);\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(695, 655, 31, 31))
        self.label_22.setStyleSheet("QLabel\n"
"{\n"
"border:none;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("Home_Icon.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(415, 90, 12, 41))
        self.label_27.setStyleSheet("background-color: black;")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.Fifth_combox = QtWidgets.QComboBox(self.centralwidget)
        self.Fifth_combox.setGeometry(QtCore.QRect(480, 190, 69, 22))
        self.Fifth_combox.setStyleSheet("QComboBox\n"
"{\n"
"border:none;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.Fifth_combox.setObjectName("Fifth_combox")
        self.Fifth_combox.addItem("")
        self.Fifth_combox.addItem("")
        self.Fifth_combox.addItem("")
        self.Fifth_combox.addItem("")
        self.Fifth_combox.addItem("")
        self.Fifth_combox.addItem("")
        self.Fifth_combox.addItem("")
        self.Fifth_combox.addItem("")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(480, 160, 71, 21))
        self.label_33.setStyleSheet("QLabel{\n"
"    background-color: rgb(187, 218, 252);\n"
"color:black;\n"
"\n"
"}")
        self.label_33.setObjectName("label_33")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(1080, 110, 12, 41))
        self.label_36.setStyleSheet("background-color: black;")
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(467, 80, 12, 60))
        self.label_39.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 0, 0);\n"
"border-radius:2px;\n"
"}")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(560, 160, 71, 21))
        self.label_42.setStyleSheet("QLabel{\n"
"    background-color: rgb(187, 218, 252);\n"
"color:black;\n"
"\n"
"}")
        self.label_42.setObjectName("label_42")
        self.Sixth_combox = QtWidgets.QComboBox(self.centralwidget)
        self.Sixth_combox.setGeometry(QtCore.QRect(560, 190, 69, 22))
        self.Sixth_combox.setStyleSheet("QComboBox\n"
"{\n"
"border:none;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.Sixth_combox.setObjectName("Sixth_combox")
        self.Sixth_combox.addItem("")
        self.Sixth_combox.addItem("")
        self.Sixth_combox.addItem("")
        self.Sixth_combox.addItem("")
        self.Sixth_combox.addItem("")
        self.Sixth_combox.addItem("")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(1127, 100, 12, 60))
        self.label_44.setText("")
        self.label_44.setObjectName("label_44")
        self.label_44.setStyleSheet("QLabel{\n"
                                    "background-color: rgb(255, 0, 0);\n"
                                    "border-radius:2px;\n"
                                    "}")
        self.Second_Resistor_TempCoeff = QtWidgets.QLineEdit(self.centralwidget)
        self.Second_Resistor_TempCoeff.setGeometry(QtCore.QRect(1150, 280, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Second_Resistor_TempCoeff.setFont(font)
        self.Second_Resistor_TempCoeff.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"text-align:center;\n"
"\n"
"}")
        self.Second_Resistor_TempCoeff.setObjectName("Second_Resistor_TempCoeff")
        self.pushButton_Band_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Band_6.setGeometry(QtCore.QRect(10, 250, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Band_6.setFont(font)
        self.pushButton_Band_6.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"opacity:0.7;\n"
"color:Black;\n"
"border:2px solid rgb(127, 110, 87);;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(51, 51, 51, 0.5);\n"
"}\n"
"")
        self.pushButton_Band_6.setObjectName("pushButton_Band_6")
        self.label.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_13.raise_()
        self.label_9.raise_()
        self.label_6.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.First_combox.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.pushButton_Band_4.raise_()
        self.pushButton_Band_5.raise_()
        self.label_32.raise_()
        self.Rsistor_value.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.Tolerance_value.raise_()
        self.label_38.raise_()
        self.Minimum_value.raise_()
        self.label_41.raise_()
        self.Maximum_value.raise_()
        self.label_37.raise_()
        self.label_40.raise_()
        self.pushButton_First_Calculate.raise_()
        self.Second_Resistor_Value.raise_()
        self.Second_Resistor_Tolerance.raise_()
        self.pushButton_Second_Calculate.raise_()
        self.label_43.raise_()
        self.Truncated_value.raise_()
        self.label_45.raise_()
        self.label_47.raise_()
        self.Second_combox.raise_()
        self.Third_combox.raise_()
        self.Fourth_combox.raise_()
        self.pushButton_Lab_Manual.raise_()
        self.label_2.raise_()
        self.label_22.raise_()
        self.pushButton_Home.raise_()
        self.label_27.raise_()
        self.Fifth_combox.raise_()
        self.label_33.raise_()
        self.label_36.raise_()
        self.label_39.raise_()
        self.label_42.raise_()
        self.Sixth_combox.raise_()
        self.label_44.raise_()
        self.Second_Resistor_TempCoeff.raise_()
        self.pushButton_Band_6.raise_()
        self.pushButton_Lab_Manual.clicked.connect(self.labe_manul)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def labe_manul(self):
            self.window = QtWidgets.QMainWindow()
            self.ui = Lab_MainWindow()
            self.ui.setupUi(self.window)
            self.window.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Resistor Color Code Calculator"))
        self.label.setText(_translate("MainWindow", "                        Resistor Color Code Calculator"))
        self.First_combox.setItemText(0, _translate("MainWindow", "Black"))
        self.First_combox.setItemText(1, _translate("MainWindow", "Brown"))
        self.First_combox.setItemText(2, _translate("MainWindow", "Red"))
        self.First_combox.setItemText(3, _translate("MainWindow", "Orange"))
        self.First_combox.setItemText(4, _translate("MainWindow", "Yellow"))
        self.First_combox.setItemText(5, _translate("MainWindow", "Green"))
        self.First_combox.setItemText(6, _translate("MainWindow", "Blue"))
        self.First_combox.setItemText(7, _translate("MainWindow", "Violet"))
        self.First_combox.setItemText(8, _translate("MainWindow", "Gray"))
        self.First_combox.setItemText(9, _translate("MainWindow", "White"))
        self.label_25.setText(_translate("MainWindow", "     1st Digit"))
        self.label_26.setText(_translate("MainWindow", "     4th Digit"))
        self.label_28.setText(_translate("MainWindow", "     3rd Digit"))
        self.label_29.setText(_translate("MainWindow", "     2nd Digit"))
        self.label_30.setText(_translate("MainWindow", "Value Display"))
        self.pushButton_Band_4.setText(_translate("MainWindow", "4-Band"))
        self.pushButton_Band_5.setText(_translate("MainWindow", "5-Band"))
        self.label_32.setText(_translate("MainWindow", "Resistance"))
        self.Rsistor_value.setText(_translate("MainWindow", "0"))
        self.label_34.setText(_translate("MainWindow", "  Ω"))
        self.label_35.setText(_translate("MainWindow", "Tolerance"))
        self.Tolerance_value.setText(_translate("MainWindow", "0"))
        self.label_38.setText(_translate("MainWindow", "Minimum Value"))
        self.Minimum_value.setText(_translate("MainWindow", "0"))
        self.label_41.setText(_translate("MainWindow", "Maximum Value"))
        self.Maximum_value.setText(_translate("MainWindow", "0"))
        self.label_37.setText(_translate("MainWindow", "  Ω"))
        self.label_40.setText(_translate("MainWindow", "  Ω"))
        self.pushButton_First_Calculate.setText(_translate("MainWindow", "Calculate"))
        self.Second_Resistor_Value.setPlaceholderText(_translate("MainWindow", "Resistor Value (Ohms)"))
        self.Second_Resistor_Tolerance.setPlaceholderText(_translate("MainWindow", "Tolerance"))
        self.pushButton_Second_Calculate.setText(_translate("MainWindow", "Calculate"))
        self.label_43.setText(_translate("MainWindow", "Truncated Value:"))
        self.Truncated_value.setText(_translate("MainWindow", "  0"))
        self.label_45.setText(_translate("MainWindow", "Standard"))
        self.Second_combox.setItemText(0, _translate("MainWindow", "Black"))
        self.Second_combox.setItemText(1, _translate("MainWindow", "Brown"))
        self.Second_combox.setItemText(2, _translate("MainWindow", "Red"))
        self.Second_combox.setItemText(3, _translate("MainWindow", "Orange"))
        self.Second_combox.setItemText(4, _translate("MainWindow", "Yellow"))
        self.Second_combox.setItemText(5, _translate("MainWindow", "Green"))
        self.Second_combox.setItemText(6, _translate("MainWindow", "Blue"))
        self.Second_combox.setItemText(7, _translate("MainWindow", "Violet"))
        self.Second_combox.setItemText(8, _translate("MainWindow", "Gray"))
        self.Second_combox.setItemText(9, _translate("MainWindow", "White"))
        self.Third_combox.setItemText(0, _translate("MainWindow", "Black"))
        self.Third_combox.setItemText(1, _translate("MainWindow", "Brown"))
        self.Third_combox.setItemText(2, _translate("MainWindow", "Red"))
        self.Third_combox.setItemText(3, _translate("MainWindow", "Orange"))
        self.Third_combox.setItemText(4, _translate("MainWindow", "Yellow"))
        self.Third_combox.setItemText(5, _translate("MainWindow", "Green"))
        self.Third_combox.setItemText(6, _translate("MainWindow", "Blue"))
        self.Third_combox.setItemText(7, _translate("MainWindow", "Violet"))
        self.Third_combox.setItemText(8, _translate("MainWindow", "Gray"))
        self.Third_combox.setItemText(9, _translate("MainWindow", "White"))
        self.Fourth_combox.setItemText(0, _translate("MainWindow", "Black"))
        self.Fourth_combox.setItemText(1, _translate("MainWindow", "Brown"))
        self.Fourth_combox.setItemText(2, _translate("MainWindow", "Red"))
        self.Fourth_combox.setItemText(3, _translate("MainWindow", "Orange"))
        self.Fourth_combox.setItemText(4, _translate("MainWindow", "Yellow"))
        self.Fourth_combox.setItemText(5, _translate("MainWindow", "Green"))
        self.Fourth_combox.setItemText(6, _translate("MainWindow", "Blue"))
        self.Fourth_combox.setItemText(7, _translate("MainWindow", "Violet"))
        self.Fourth_combox.setItemText(8, _translate("MainWindow", "Gray"))
        self.Fourth_combox.setItemText(9, _translate("MainWindow", "White"))
        self.Fourth_combox.setItemText(10, _translate("MainWindow", "Gold"))
        self.Fourth_combox.setItemText(11, _translate("MainWindow", "Silver"))
        self.pushButton_Lab_Manual.setText(_translate("MainWindow", "Lab Manual"))
        self.Fifth_combox.setItemText(0, _translate("MainWindow", "Brown"))
        self.Fifth_combox.setItemText(1, _translate("MainWindow", "Red"))
        self.Fifth_combox.setItemText(2, _translate("MainWindow", "Green"))
        self.Fifth_combox.setItemText(3, _translate("MainWindow", "Blue"))
        self.Fifth_combox.setItemText(4, _translate("MainWindow", "Violet"))
        self.Fifth_combox.setItemText(5, _translate("MainWindow", "Gray"))
        self.Fifth_combox.setItemText(6, _translate("MainWindow", "Gold"))
        self.Fifth_combox.setItemText(7, _translate("MainWindow", "Silver"))
        self.label_33.setText(_translate("MainWindow", "     5th Digit"))
        self.label_42.setText(_translate("MainWindow", "     6th Digit"))
        self.Sixth_combox.setItemText(0, _translate("MainWindow", "Brown"))
        self.Sixth_combox.setItemText(1, _translate("MainWindow", "Red"))
        self.Sixth_combox.setItemText(2, _translate("MainWindow", "Orange"))
        self.Sixth_combox.setItemText(3, _translate("MainWindow", "Yellow"))
        self.Sixth_combox.setItemText(4, _translate("MainWindow", "Blue"))
        self.Sixth_combox.setItemText(5, _translate("MainWindow", "Violet"))
        self.Second_Resistor_TempCoeff.setPlaceholderText(_translate("MainWindow", "TCR(ppm/k)"))
        self.pushButton_Band_6.setText(_translate("MainWindow", "6-Band"))
        self.pushButton_Band_4.clicked.connect(self.four_band_clicked)
        self.pushButton_Band_5.clicked.connect(self.five_band_clicked)
        self.pushButton_Band_6.clicked.connect(self.six_band_clicked)
        self.pushButton_First_Calculate.clicked.connect(self.check_button_click)
        self.pushButton_Second_Calculate.clicked.connect(self.check_secondbutton_click)

    def check_secondbutton_click(self):
        print("called")
        try:
                if check == "four":
                        self.right_4bandresistor_coloring()
                elif check == "five":
                        self.right_5bandresistor_coloring()
                elif check == "six":
                        self.right_6bandresistor_coloring()
        except:
                print("into")
                self.right_6bandresistor_coloring()


    def check_button_click(self):

            try:
                    if check == "four":
                        self.first_resistor_coloring()
                    elif check == "five":
                         self.second_resistor_coloring()
                    elif check == "six":
                         self.third_resistor_coloring()
            except:
                    self.third_resistor_coloring()

    def make_global(self, c):
            global check
            check = c

    def four_band_clicked(self):
        self.Fifth_combox.close()
        self.Sixth_combox.close()
        self.label_33.close()
        self.label_42.close()
        self.label_27.close()
        self.label_39.close()
        self.label_36.close()
        self.label_44.close()
        self.Second_Resistor_TempCoeff.close()
        self.make_global("four")

    def five_band_clicked(self):
            self.Fifth_combox.show()
            self.label_33.show()
            self.label_27.show()
            self.label_36.show()
            self.Sixth_combox.close()
            self.label_42.close()
            self.label_39.close()
            self.label_44.close()
            self.Second_Resistor_TempCoeff.close()
            self.make_global("five")

    def six_band_clicked(self):
            self.Fifth_combox.show()
            self.Sixth_combox.show()
            self.label_33.show()
            self.label_42.show()
            self.label_27.show()
            self.label_39.show()
            self.label_36.show()
            self.label_44.show()
            self.Second_Resistor_TempCoeff.show()
            self.make_global("six")

    def labelColorChanger(self):
            self.label_6.setStyleSheet("QLabel{\n"
                                       f"background-color:{(self.First_combox.currentText())};\n"
                                       "border-radius:2px;\n"
                                       "}")
            self.label_10.setStyleSheet("QLabel{\n"
                                        f"background-color:{(self.Second_combox.currentText())};\n"
                                        "border-radius:2px;\n"
                                        "}")
            self.label_11.setStyleSheet("QLabel{\n"
                                        f"background-color:{(self.Third_combox.currentText())};\n"
                                        "border-radius:2px;\n"
                                        "}")
            self.label_12.setStyleSheet("QLabel{\n"
                                        f"background-color:{(self.Fourth_combox.currentText())};\n"
                                        "border-radius:2px;\n"
                                        "}")

    def first_resistor_coloring(self):
        self.labelColorChanger()
        value = Tolerance_Maping.tolerance4_mapping(self.Fourth_combox.currentText())
        self.Tolerance_value.setText(value)
        first_digit = int(Color_Mapper.color_mapper(self.First_combox.currentText())) * 10
        second_digit = int(Color_Mapper.color_mapper(self.Second_combox.currentText()))
        multiplier = 10 ** int(Color_Mapper.color_mapper(self.Third_combox.currentText()))
        resistance_value = (first_digit + second_digit) * multiplier
        print(resistance_value)
        valu = float(value)
        print(valu)
        output_resistance_value = str(resistance_value)
        self.Rsistor_value.setText(output_resistance_value)
        max_value = (resistance_value * (valu)) + resistance_value
        mini_value = resistance_value - (resistance_value * valu)
        maxi = str(max_value)
        mini = str(mini_value)
        self.Maximum_value.setText(maxi)
        self.Minimum_value.setText(mini)

    def second_resistor_coloring(self):
            self.labelColorChanger()
            self.label_27.setStyleSheet("QLabel{\n"
                                                f"background-color:{(self.Fifth_combox.currentText())};\n"
                                                "border-radius:2px;\n"
                                                "}")
            value = Tolerance_Maping.tolerance_mapping(self.Fifth_combox.currentText())
            self.Tolerance_value.setText(value)
            first_digit = int(Color_Mapper.color_mapper(self.First_combox.currentText())) * 100
            second_digit = int(Color_Mapper.color_mapper(self.Second_combox.currentText())) * 10
            third_digit = int(Color_Mapper.color_mapper(self.Third_combox.currentText()))
            multiplier = 10 ** int(Color_Mapper.color_mapper(self.Fourth_combox.currentText()))
            resistance_value = (first_digit + second_digit + third_digit) * multiplier
            print(resistance_value)
            valu = float(value)
            print(valu)
            output_resistance_value = str(resistance_value)
            self.Rsistor_value.setText(output_resistance_value)
            max_value = (resistance_value * (valu)) + resistance_value
            mini_value = resistance_value - (resistance_value * valu)
            maxi = str(max_value)
            mini = str(mini_value)
            self.Maximum_value.setText(maxi)
            self.Minimum_value.setText(mini)

    def third_resistor_coloring(self):

            self.labelColorChanger()
            self.label_27.setStyleSheet("QLabel{\n"
                                                f"background-color:{(self.Fifth_combox.currentText())};\n"
                                                "border-radius:2px;\n"
                                                "}")
            self.label_39.setStyleSheet("QLabel{\n"
                                                f"background-color:{(self.Sixth_combox.currentText())};\n"
                                                "border-radius:2px;\n"
                                                "}")
            value = Tolerance_Maping.tolerance_mapping(self.Fifth_combox.currentText())
            self.Tolerance_value.setText(value)
            first_digit = int(Color_Mapper.color_mapper(self.First_combox.currentText())) * 100
            second_digit = int(Color_Mapper.color_mapper(self.Second_combox.currentText())) * 10
            third_digit = int(Color_Mapper.color_mapper(self.Third_combox.currentText()))
            multiplier = 10 ** int(Color_Mapper.color_mapper(self.Fourth_combox.currentText()))
            resistance_value = (first_digit + second_digit + third_digit) * multiplier
            print(resistance_value)
            valu = float(value)
            print(valu)
            output_resistance_value = str(resistance_value)
            self.Rsistor_value.setText(output_resistance_value)
            max_value = (resistance_value * (valu)) + resistance_value
            mini_value = resistance_value - (resistance_value * valu)
            maxi = str(max_value)
            mini = str(mini_value)
            self.Maximum_value.setText(maxi)
            self.Minimum_value.setText(mini)


    def first3labelscolor(self, band_value):
            self.label_18.setStyleSheet("QLabel{\n"
                                        f"background-color:{Color_Mapper.reverse_color(band_value[0])};\n"
                                        "border-radius:2px;\n"
                                        "}")

            self.label_19.setStyleSheet("QLabel{\n"
                                f"background-color:{Color_Mapper.reverse_color(band_value[1])};\n"
                                "border-radius:2px;\n"
                                "}")
            self.label_20.setStyleSheet("QLabel{\n"
                                f"background-color:{Color_Mapper.reverse_color(band_value[2])};\n"
                                "border-radius:2px;\n"
                                "}")



    def right_4bandresistor_coloring(self):

            resistor = " "
            dotcount = 0
            resistor1 = self.Second_Resistor_Value.text()
            for count in resistor1:
                    if count in "0123456789.":
                            resistor += count

            self.Truncated_value.setText("  " + str(int(float(resistor))) + " Ohm")
            band_value = []
            for v in str(int(float(resistor))):
                    band_value.append(v)

            if len(band_value) > 2:
                    multiplier = str(len(band_value) - 2)

                    self.label_20.setStyleSheet("QLabel{\n"
                                                f"background-color:{Color_Mapper.reverse_color(multiplier)};\n"
                                                "border-radius:2px;\n"
                                                "}")

                    self.label_18.setStyleSheet("QLabel{\n"
                                        f"background-color:{Color_Mapper.reverse_color(band_value[0])};\n"
                                        "border-radius:2px;\n"
                                        "}")

                    self.label_19.setStyleSheet("QLabel{\n"
                                        f"background-color:{Color_Mapper.reverse_color(band_value[1])};\n"
                                        "border-radius:2px;\n"
                                        "}")

            if len(band_value) < 3:

                    self.label_20.setStyleSheet("QLabel{\n"
                                                f"background-color: black;\n"
                                                "border-radius:2px;\n""}")

                    if len(band_value) == 2:
                           self.label_18.setStyleSheet("QLabel{\n"
                                        f"background-color:{Color_Mapper.reverse_color(band_value[0])};\n"
                                        "border-radius:2px;\n"
                                        "}")

                           self.label_19.setStyleSheet("QLabel{\n"
                                        f"background-color:{Color_Mapper.reverse_color(band_value[1])};\n"
                                        "border-radius:2px;\n"
                                        "}")

                    elif len(band_value) == 1:
                            self.label_18.setStyleSheet("QLabel{\n"
                                                        f"background-color:{Color_Mapper.reverse_color(band_value[0])};\n"
                                                        "border-radius:2px;\n"
                                                        "}")

                            self.label_19.setStyleSheet("QLabel{\n"
                                                        f"background-color:black;\n"
                                                        "border-radius:2px;\n"
                                                        "}")
                            self.label_20.setStyleSheet("QLabel{\n"
                                                        f"background-color:black;\n"
                                                        "border-radius:2px;\n"
                                                        "}")

            toleranceList = ["0.01", "0.02", "0.005", "0.0025", "0.001", "0.0005", "0.05", "0.1"]

            if self.Second_Resistor_Tolerance.text() in toleranceList:
                    self.label_21.setStyleSheet("QLabel{\n"
                                                f"background-color:{Tolerance_Maping.reverse_tolerance_mapping(self.Second_Resistor_Tolerance.text())};\n"
                                                "}")
            else:

                    self.Second_Resistor_Tolerance.clear()


    def right_5bandresistor_coloring(self):

            resistor = " "
            dotcount = 0
            resistor1 = self.Second_Resistor_Value.text()
            for count in resistor1:
                    if count in "0123456789.":
                            resistor += count

            self.Truncated_value.setText("  " + str(int(float(resistor))) + " Ohm")
            band_value = []
            for v in str(int(float(resistor))):
                    band_value.append(v)

            if len(band_value) > 3:
                    multiplier = str(len(band_value) - 3)

                    self.label_21.setStyleSheet("QLabel{\n"
                                                f"background-color:{Color_Mapper.reverse_color(multiplier)};\n"
                                                "border-radius:2px;\n"
                                                "}")

                    self.first3labelscolor(band_value)

            if len(band_value) < 4:

                    self.label_21.setStyleSheet("QLabel{\n"
                                                f"background-color: black;\n"
                                                "border-radius:2px;\n""}")

                    if len(band_value) == 3:
                            self.first3labelscolor(band_value)
                    elif len(band_value) == 2:
                            self.label_18.setStyleSheet("QLabel{\n"
                                                        f"background-color:{Color_Mapper.reverse_color(band_value[0])};\n"
                                                        "border-radius:2px;\n"
                                                        "}")

                            self.label_19.setStyleSheet("QLabel{\n"
                                                        f"background-color:{Color_Mapper.reverse_color(band_value[1])};\n"
                                                        "border-radius:2px;\n"
                                                        "}")
                            self.label_20.setStyleSheet("QLabel{\n"
                                                        f"background-color:black;\n"
                                                        "border-radius:2px;\n"
                                                        "}")
                    elif len(band_value) == 1:
                            self.label_18.setStyleSheet("QLabel{\n"
                                                        f"background-color:{Color_Mapper.reverse_color(band_value[0])};\n"
                                                        "border-radius:2px;\n"
                                                        "}")
                            self.label_19.setStyleSheet("QLabel{\n"
                                                        f"background-color:black;\n"
                                                        "border-radius:2px;\n"
                                                        "}")
                            self.label_20.setStyleSheet("QLabel{\n"
                                                        f"background-color:black;\n"
                                                        "border-radius:2px;\n"
                                                        "}")

            toleranceList = ["0.01", "0.02", "0.005", "0.0025", "0.001", "0.0005", "0.05", "0.1"]

            if self.Second_Resistor_Tolerance.text() in toleranceList:
                    self.label_36.setStyleSheet("QLabel{\n"
                                                f"background-color:{Tolerance_Maping.reverse_tolerance_mapping(self.Second_Resistor_Tolerance.text())};\n"
                                                "}")
            else:

                    self.Second_Resistor_Tolerance.clear()


    def right_6bandresistor_coloring(self):

            self.right_5bandresistor_coloring()

            coeffficientList = ["100", "50", "15", "25", "10", "5"]

            if self.Second_Resistor_TempCoeff.text() in coeffficientList:
                    self.label_44.setStyleSheet("QLabel{\n"
                                                f"background-color:{Temperature_Coefficient_Mapping.Temperature_mapping(self.Second_Resistor_TempCoeff.text())};\n"
                                                "border-radius:2px;\n""}")
            else:

                    self.Second_Resistor_TempCoeff.clear()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Resistor_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
