# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Splash_screen_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Main_Window import *
from Multi_Band_Resistor_Color_Code_Calculator import *


class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(618, 399)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, -1, 621, 401))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("mit-wave-computing-circuit-design-ie_resize_md.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 120, 491, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"color:white;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(250, 240, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(23, 53, 109);\n"
"\n"
"}\n"
                                      
"QPushButton:hover{\n"
"    background-color: #333;\n"
"    color: orange;\n"
"\n"
"}")

        self.pushButton.setAutoDefault(True)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.dis_player)
        self.pushButton.setToolTip("Click this button to open the simulations")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        global  My_AllMainWindow
        self.My_AllMainWindow = QtWidgets.QMainWindow()
        self.ui = my_MainWindow()
        self.ui.setupUi(self.My_AllMainWindow)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "UG ECE Basic Laboratory Simulation Software "))
        self.label_2.setText(_translate("Dialog", "Interactive Simulation for UG ECE \n"
        " Basic Laboratory Experiments"))
        self.pushButton.setText(_translate("Dialog", "EXPLORE"))

    def dis_player(self):

        if Dialog.isVisible():
            Dialog.hide()

        if self.My_AllMainWindow.isVisible():
            self.My_AllMainWindow.hide()

        else:
            self.My_AllMainWindow.show()



        # self.window = QtWidgets.QMainWindow()
        # self.ui = MyMainWindow()
        # self.ui.setupUi(self.window)
        # self.window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())


