# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Star_Delta_Circuit.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QListWidgetItem
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QSize

class star_delta_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1371, 705)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    \n"
"    background-color: rgb(234, 234, 234);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-90, -10, 1500, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(50, 75, 97);\n"
"    color: White;\n"
"}")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 60, 844, 561))
        self.label_3.setStyleSheet("QLabel{    \n"
"    background-color: rgb(54, 248, 100, 0.2);\n"
"border-radius:40px;\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1141, 120, 181, 241))
        self.label_4.setStyleSheet("QLabel{\n"
"    \n"
"    \n"
"    background-color: rgb(62, 62, 62);\n"
"border-radius:40px;\n"
"border: 10px solid;\n"
"    \n"
"    border-color: rgb(255, 170, 0);\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(20, 160, 151, 311))
        self.label_31.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: white;\n"
"border-radius:40px;\n"
"border: 2px solid;\n"
"    border-color: rgb(127, 110, 87);\n"
"}")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.pushButton_Lab_Manual = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Lab_Manual.setGeometry(QtCore.QRect(1230, 0, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Lab_Manual.setFont(font)
        self.pushButton_Lab_Manual.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Lab_Manual.setStyleSheet("QPushButton\n"
"{\n"
"border:none;\n"
"color:white;\n"
"    background-color: rgb(127, 110, 87);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(51, 51, 51, 0.5);\n"
"}")
        self.pushButton_Lab_Manual.setObjectName("pushButton_Lab_Manual")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(695, 655, 31, 31))
        self.label_22.setStyleSheet("QLabel\n"
"{\n"
"border:none;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("Home_Icon.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1100, 5, 31, 31))
        self.label_2.setStyleSheet("background-color: rgb(50, 75, 97);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("run_icon.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton_Run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Run.setGeometry(QtCore.QRect(1090, 0, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Run.setFont(font)
        self.pushButton_Run.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Run.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(51, 51, 51, 0);\n"
"color:white;\n"
"border:none;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(51, 51, 51, 0.5);\n"
"}")
        self.pushButton_Run.setText("")
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1150, 10, 31, 21))
        self.label_5.setStyleSheet("background-color: rgb(50, 75, 97);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Stop-icon.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setGeometry(QtCore.QRect(1140, 0, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_stop.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(51, 51, 51, 0);\n"
"color:white;\n"
"border:none;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(51, 51, 51, 0.5);\n"
"}")
        self.pushButton_stop.setText("")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.Multimeter_value_displayer = QtWidgets.QLabel(self.centralwidget)
        self.Multimeter_value_displayer.setGeometry(QtCore.QRect(1161, 140, 141, 91))
        self.Multimeter_value_displayer.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: white;\n"
"border-radius:20px;\n"
"border: 2px solid;\n"
"    border-color: rgb(127, 110, 87);\n"
"}")
        self.Multimeter_value_displayer.setText("")
        self.Multimeter_value_displayer.setObjectName("Multimeter_value_displayer")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1155, 290, 30, 30))
        self.label_11.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: black;\n"
"border-radius:15px;\n"
"border: 4px solid;\n"
"    border-color: rgb(127, 110, 87);\n"
"}")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1195, 290, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: black;\n"
"border-radius:15px;\n"
"border: 4px solid;\n"
"    border-color: rgb(127, 110, 87);\n"
"}")
        self.label_12.setText("")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(1235, 290, 30, 30))
        self.label_13.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: black;\n"
"border-radius:15px;\n"
"border: 4px solid;\n"
"    border-color: rgb(127, 110, 87);\n"
"}")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(1275, 290, 30, 30))
        self.label_14.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: black;\n"
"border-radius:15px;\n"
"border: 4px solid;\n"
"    border-color: rgb(127, 110, 87);\n"
"}")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(1154, 260, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(1234, 260, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(1194, 260, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.Voltage_Measurement_port = QtWidgets.QLabel(self.centralwidget)
        self.Voltage_Measurement_port.setGeometry(QtCore.QRect(1162, 297, 16, 16))
        self.Voltage_Measurement_port.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: black;\n"
"border-radius:8px;\n"
"border: 4px solid;\n"
"    \n"
"    border-color: rgb(85, 0, 0);\n"
"}")
        self.Voltage_Measurement_port.setText("")
        self.Voltage_Measurement_port.setObjectName("Voltage_Measurement_port")
        self.current_measurement_port = QtWidgets.QLabel(self.centralwidget)
        self.current_measurement_port.setGeometry(QtCore.QRect(1202, 297, 16, 16))
        self.current_measurement_port.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: black;\n"
"border-radius:8px;\n"
"border: 4px solid;\n"
"    \n"
"    border-color: rgb(85, 0, 0);\n"
"}")
        self.current_measurement_port.setText("")
        self.current_measurement_port.setObjectName("current_measurement_port")
        self.resistance_measurement_port = QtWidgets.QLabel(self.centralwidget)
        self.resistance_measurement_port.setGeometry(QtCore.QRect(1242, 297, 16, 16))
        self.resistance_measurement_port.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: black;\n"
"border-radius:8px;\n"
"border: 4px solid;\n"
"    \n"
"    border-color: rgb(85, 0, 0);\n"
"}")
        self.resistance_measurement_port.setText("")
        self.resistance_measurement_port.setObjectName("resistance_measurement_port")
        self.Common_port = QtWidgets.QLabel(self.centralwidget)
        self.Common_port.setGeometry(QtCore.QRect(1282, 297, 16, 16))
        self.Common_port.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: black;\n"
"border-radius:8px;\n"
"border: 4px solid;\n"
"    \n"
"    border-color: rgb(170, 113, 0);\n"
"}")
        self.Common_port.setText("")
        self.Common_port.setObjectName("Common_port")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(1267, 260, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.R1_value = QtWidgets.QLineEdit(self.centralwidget)
        self.R1_value.setGeometry(QtCore.QRect(630, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.R1_value.setFont(font)
        self.R1_value.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}")
        self.R1_value.setText("")
        self.R1_value.setObjectName("R1_value")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(450, 530, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("background-color: rgb(198, 237, 207);\n"
"color: rgb(71, 0, 0);")
        self.label_32.setObjectName("label_32")
        self.listWidget_Drag_YD = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_Drag_YD.setGeometry(QtCore.QRect(45, 200, 105, 111))
        self.listWidget_Drag_YD.setStyleSheet("QListWidget{\n"
"border: 1px solid;\n"
"border-right-color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"border-top-color: rgb(255, 255, 255);\n"
"border-left-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.listWidget_Drag_YD.setObjectName("listWidget_Drag_YD")
        self.listWidget_Drag_V1 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_Drag_V1.setGeometry(QtCore.QRect(70, 345, 61, 81))
        self.listWidget_Drag_V1.setStyleSheet("QListWidget{\n"
"border: 1px solid;\n"
"border-right-color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"border-top-color: rgb(255, 255, 255);\n"
"border-left-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.listWidget_Drag_V1.setObjectName("listWidget_Drag_V1")
        self.listWidget_Drop_V1 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_Drop_V1.setGeometry(QtCore.QRect(489, 255, 64, 100))
        self.listWidget_Drop_V1.setStyleSheet("QListWidget{\n"
"border-radius: 20px;\n"
"border: 2px dashed;\n"
"border-color: rgb(170, 125, 111, 0.2);\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.listWidget_Drop_V1.setObjectName("listWidget_Drop_V1")
        self.listWidget_Drop_YD = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_Drop_YD.setEnabled(True)
        self.listWidget_Drop_YD.setGeometry(QtCore.QRect(710, 120, 251, 231))
        self.listWidget_Drop_YD.setStyleSheet("QListWidget{\n"
"border: 2px dashed;\n"
"border-color: rgb(170, 125, 111, 0.2);\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.listWidget_Drop_YD.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget_Drop_YD.setObjectName("listWidget_Drop_YD")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(460, 290, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(198, 237, 207);\n"
"color: rgb(71, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.R2_value = QtWidgets.QLineEdit(self.centralwidget)
        self.R2_value.setGeometry(QtCore.QRect(630, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.R2_value.setFont(font)
        self.R2_value.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}")
        self.R2_value.setText("")
        self.R2_value.setObjectName("R2_value")
        self.R6_value = QtWidgets.QLineEdit(self.centralwidget)
        self.R6_value.setGeometry(QtCore.QRect(640, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.R6_value.setFont(font)
        self.R6_value.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}")
        self.R6_value.setText("")
        self.R6_value.setObjectName("R6_value")
        self.R3_value = QtWidgets.QLineEdit(self.centralwidget)
        self.R3_value.setGeometry(QtCore.QRect(640, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.R3_value.setFont(font)
        self.R3_value.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}")
        self.R3_value.setText("")
        self.R3_value.setObjectName("R3_value")
        self.V1_value = QtWidgets.QLineEdit(self.centralwidget)
        self.V1_value.setGeometry(QtCore.QRect(630, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.V1_value.setFont(font)
        self.V1_value.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}")
        self.V1_value.setText("")
        self.V1_value.setObjectName("V1_value")
        self.YD_top_label = QtWidgets.QPushButton(self.centralwidget)
        self.YD_top_label.setGeometry(QtCore.QRect(675, 120, 36, 36))
        self.YD_top_label.setStyleSheet("QPushButton{\n"
"border-radius: 18px;\n"
"border: 2px dashed;\n"
"border-color: rgb(170, 125, 111, 0.2);\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.YD_top_label.setText("")
        self.YD_top_label.setObjectName("YD_top_label")
        self.V1_bottom_label = QtWidgets.QPushButton(self.centralwidget)
        self.V1_bottom_label.setGeometry(QtCore.QRect(500, 350, 36, 36))
        self.V1_bottom_label.setStyleSheet("QPushButton{\n"
"border-radius: 18px;\n"
"border: 2px dashed;\n"
"border-color: rgb(170, 125, 111, 0.2);\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.V1_bottom_label.setText("")
        self.V1_bottom_label.setObjectName("V1_bottom_label")
        self.YD_bottom_label = QtWidgets.QPushButton(self.centralwidget)
        self.YD_bottom_label.setGeometry(QtCore.QRect(810, 350, 36, 36))
        self.YD_bottom_label.setStyleSheet("QPushButton{\n"
"border-radius: 18px;\n"
"border: 2px dashed;\n"
"border-color: rgb(170, 125, 111, 0.2);\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.YD_bottom_label.setText("")
        self.YD_bottom_label.setObjectName("YD_bottom_label")
        self.V1_top_label = QtWidgets.QPushButton(self.centralwidget)
        self.V1_top_label.setGeometry(QtCore.QRect(501, 220, 36, 36))
        self.V1_top_label.setStyleSheet("QPushButton{\n"
"border-radius: 18px;\n"
"border: 2px dashed;\n"
"border-color: rgb(170, 125, 111, 0.2);\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.V1_top_label.setText("")
        self.V1_top_label.setObjectName("V1_top_label")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(515, 460, 317, 7))
        self.label_16.setStyleSheet("background-color: rgb(200, 136, 91);\n"
"border-radius:3px;")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(515, 135, 7, 125))
        self.label_24.setStyleSheet("background-color: rgb(200, 136, 91);\n"
"border-radius:3px;")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.pushButton_Ok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Ok.setGeometry(QtCore.QRect(780, 530, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_Ok.setFont(font)
        self.pushButton_Ok.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_Ok.setObjectName("pushButton_Ok")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(515, 345, 7, 120))
        self.label_28.setStyleSheet("background-color: rgb(200, 136, 91);\n"
"border-radius:3px;")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(517, 135, 205, 7))
        self.label_29.setStyleSheet("background-color: rgb(200, 136, 91);\n"
"border-radius:3px;")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(825, 340, 7, 125))
        self.label_36.setStyleSheet("background-color: rgb(200, 136, 91);\n"
"border-radius:3px;")
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.pushButton_Home = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Home.setGeometry(QtCore.QRect(690, 650, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Home.setFont(font)
        self.pushButton_Home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Home.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(51, 51, 51, 0);\n"
"color:white;\n"
"border:none;\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(51, 51, 51, 0.5);\n"
"}")
        self.pushButton_Home.setText("")
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(755, 220, 40, 40))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"

"background-color: rgb(198, 237, 207, 0);\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(778, 178, 40, 40))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"

"background-color: rgb(198, 237, 207, 0);\n"
"}")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(813, 245, 31, 51))
        self.pushButton_6.setStyleSheet("QPushButton{\n"

"background-color: rgb(198, 237, 207, 0);\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(845, 180, 40, 40))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"

"background-color: rgb(198, 237, 207, 0);\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(805, 123, 51, 31))
        self.pushButton_1.setStyleSheet("QPushButton{\n"
"background-color: rgb(198, 237, 207, 0);\n"
"}")
        self.pushButton_1.setText("")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(870, 215, 40, 40))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"

"background-color: rgb(198, 237, 207, 0);\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.R5_value = QtWidgets.QLineEdit(self.centralwidget)
        self.R5_value.setGeometry(QtCore.QRect(630, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.R5_value.setFont(font)
        self.R5_value.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}")
        self.R5_value.setText("")
        self.R5_value.setObjectName("R5_value")
        self.R4_value = QtWidgets.QLineEdit(self.centralwidget)
        self.R4_value.setGeometry(QtCore.QRect(640, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.R4_value.setFont(font)
        self.R4_value.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}")
        self.R4_value.setText("")
        self.R4_value.setObjectName("R4_value")
        self.R1_Result = QtWidgets.QPushButton(self.centralwidget)
        self.R1_Result.setGeometry(QtCore.QRect(810, 100, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.R1_Result.setFont(font)
        self.R1_Result.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.R1_Result.setObjectName("R1_Result")
        self.R3_Result = QtWidgets.QPushButton(self.centralwidget)
        self.R3_Result.setGeometry(QtCore.QRect(710, 200, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.R3_Result.setFont(font)
        self.R3_Result.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.R3_Result.setObjectName("R3_Result")
        self.R4_Result = QtWidgets.QPushButton(self.centralwidget)
        self.R4_Result.setGeometry(QtCore.QRect(770, 150, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.R4_Result.setFont(font)
        self.R4_Result.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.R4_Result.setObjectName("R4_Result")
        self.R5_Result = QtWidgets.QPushButton(self.centralwidget)
        self.R5_Result.setGeometry(QtCore.QRect(835, 158, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.R5_Result.setFont(font)
        self.R5_Result.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.R5_Result.setObjectName("R5_Result")
        self.R6_Result = QtWidgets.QPushButton(self.centralwidget)
        self.R6_Result.setGeometry(QtCore.QRect(770, 300, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.R6_Result.setFont(font)
        self.R6_Result.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.R6_Result.setObjectName("R6_Result")
        self.R2_Result = QtWidgets.QPushButton(self.centralwidget)
        self.R2_Result.setGeometry(QtCore.QRect(910, 220, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.R2_Result.setFont(font)
        self.R2_Result.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background-color: rgb(198, 237, 207);\n"
"}")
        self.R2_Result.setObjectName("R2_Result")
        self.label_3.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_31.raise_()
        self.pushButton_Lab_Manual.raise_()
        self.label_22.raise_()
        self.label_2.raise_()
        self.pushButton_Run.raise_()
        self.label_5.raise_()
        self.pushButton_stop.raise_()
        self.Multimeter_value_displayer.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.Voltage_Measurement_port.raise_()
        self.current_measurement_port.raise_()
        self.resistance_measurement_port.raise_()
        self.Common_port.raise_()
        self.label_19.raise_()
        self.R1_value.raise_()
        self.label_32.raise_()
        self.listWidget_Drag_YD.raise_()
        self.listWidget_Drag_V1.raise_()
        self.listWidget_Drop_V1.raise_()
        self.listWidget_Drop_YD.raise_()
        self.label_8.raise_()
        self.R2_value.raise_()
        self.R3_value.raise_()
        self.YD_top_label.raise_()
        self.V1_bottom_label.raise_()
        self.YD_bottom_label.raise_()
        self.V1_top_label.raise_()
        self.label_16.raise_()
        self.label_24.raise_()
        self.pushButton_Ok.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_36.raise_()
        self.pushButton_Home.raise_()
        self.R4_value.raise_()
        self.R5_value.raise_()
        self.R6_value.raise_()
        self.V1_value.raise_()
        self.pushButton_3.raise_()
        self.pushButton_2.raise_()
        self.pushButton_5.raise_()
        self.pushButton_1.raise_()
        self.pushButton_4.raise_()
        self.pushButton_6.raise_()
        self.R1_Result.raise_()
        self.R3_Result.raise_()
        self.R4_Result.raise_()
        self.R5_Result.raise_()
        self.R6_Result.raise_()
        self.R2_Result.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.R1_Result.clicked.connect(self.showR1properties)
        self.R2_Result.clicked.connect(self.showR2properties)
        self.R3_Result.clicked.connect(self.showR3properties)
        self.R4_Result.clicked.connect(self.showR4properties)
        self.R5_Result.clicked.connect(self.showR5properties)
        self.R6_Result.clicked.connect(self.showR6properties)
        self.pushButton_Ok.clicked.connect(self.assign_Values)
        self.listWidget_Drop_V1.clicked.connect(self.set_V1_value)
        self.pushButton_1.clicked.connect(self.set_R1_value)
        self.pushButton_2.clicked.connect(self.set_R2_value)
        self.pushButton_3.clicked.connect(self.set_R3_value)
        self.pushButton_4.clicked.connect(self.set_R4_value)
        self.pushButton_5.clicked.connect(self.set_R5_value)
        self.pushButton_6.clicked.connect(self.set_R6_value)
        self.pushButton_Run.clicked.connect(self.simulate)
        self.V1_top_label.clicked.connect(lambda: self.set_button_value(1))
        self.YD_top_label.clicked.connect(lambda: self.set_button_value(2))
        self.V1_bottom_label.clicked.connect(lambda: self.set_button_value(3))
        self.YD_bottom_label.clicked.connect(lambda: self.set_button_value(4))
        self.pushButton_Run.clicked.connect(self.simulate)
        self.V1_value.setText("0")
        self.R1_value.setText("0")
        self.R2_value.setText("0")
        self.R3_value.setText("0")
        self.R4_value.setText("0")
        self.R5_value.setText("0")
        self.R6_value.setText("0")

    def set_button_value(self, c):
            if c == 1:
                    self.V1_top_label = 1
            elif c == 2:
                    self.YD_top_label = 1
            if c == 3:
                    self.V1_bottom_label = 1

            elif c == 4:
                    self.YD_bottom_label = 1

            self.all_button_clicked()

    def all_button_clicked(self):
            if self.V1_top_label == 1 and self.YD_top_label == 1:
                    self.label_24.show()
                    self.label_29.show()

            if self.V1_bottom_label == 1 and self.YD_bottom_label == 1:
                    self.label_28.show()
                    self.label_16.show()
                    self.label_36.show()

    def set_V1_value(self):
            self.V1_value.show()
            self.R1_value.hide()
            self.R2_value.hide()
            self.R3_value.hide()
            self.R4_value.hide()
            self.R5_value.hide()
            self.R6_value.hide()

    def set_R1_value(self):
            self.V1_value.hide()
            self.R1_value.show()
            self.R2_value.hide()
            self.R3_value.hide()
            self.R4_value.hide()
            self.R5_value.hide()
            self.R6_value.hide()

    def set_R2_value(self):
            self.V1_value.hide()
            self.R1_value.hide()
            self.R2_value.show()
            self.R3_value.hide()
            self.R4_value.hide()
            self.R5_value.hide()
            self.R6_value.hide()

    def set_R3_value(self):
            self.V1_value.hide()
            self.R1_value.hide()
            self.R2_value.hide()
            self.R3_value.show()
            self.R4_value.hide()
            self.R5_value.hide()
            self.R6_value.hide()

    def set_R4_value(self):
            self.V1_value.hide()
            self.R1_value.hide()
            self.R2_value.hide()
            self.R3_value.hide()
            self.R4_value.show()
            self.R5_value.hide()
            self.R6_value.hide()

    def set_R5_value(self):
            self.V1_value.hide()
            self.R1_value.hide()
            self.R2_value.hide()
            self.R3_value.hide()
            self.R4_value.hide()
            self.R5_value.show()
            self.R6_value.hide()

    def set_R6_value(self):
            self.V1_value.hide()
            self.R1_value.hide()
            self.R2_value.hide()
            self.R3_value.hide()
            self.R4_value.hide()
            self.R5_value.hide()
            self.R6_value.show()

    def showR1properties(self):
            self.R1 = float(self.r1)
            self.R2 = float(self.r2)
            self.R3 = float(self.r3)
            self.R4 = float(self.r4)
            self.R5 = float(self.r5)
            self.R6 = float(self.r6)
            self.V1 = float(self.v1)
            self.I1 = self.V1 / self.R3
            self.I2 = (self.V1) * ((1 - (self.R4) + (self.R6) - (self.R4 * self.R6 / (self.R3 * self.R5)))) / (
                    -self.R4 - (self.R6 / self.R5) * (self.R4 + self.R1 + self.R5))
            self.I3 = (self.V1) * ((1 - (self.R4 + self.R6) / self.R3)) + self.R4 * self.I2 / -(self.R6)
            V1 = self.I2 * self.R1

            self.Multimeter_value_displayer.setText(
                    " R1 = {0}Ω \n V1 = {1}V \n I = {2}A".format(self.R1_value.text(), round(V1, 3), round(self.I1, 3)))

    def showR2properties(self):

            self.R1 = float(self.r1)
            self.R2 = float(self.r2)
            self.R3 = float(self.r3)
            self.R4 = float(self.r4)
            self.R5 = float(self.r5)
            self.R6 = float(self.r6)
            self.V1 = float(self.v1)
            self.I1 = self.V1 / self.R3
            self.I2 = (self.V1) * ((1 - (self.R4) + (self.R6) - (self.R4 * self.R6 / (self.R3 * self.R5)))) / (
                    -self.R4 - (self.R6 / self.R5) * (self.R4 + self.R1 + self.R5))
            self.I3 = (self.V1) * ((1 - (self.R4 + self.R6) / self.R3)) + self.R4 * self.I2 / -(self.R6)
            self.Multimeter_value_displayer.setText(" R2 = {0}Ω \n V1 = {1}V \n I1 = {2}A".format(self.R2_value.text(), round(self.V1, 3), round(self.I1, 3)))

    def showR3properties(self):
            self.R1 = float(self.r1)
            self.R2 = float(self.r2)
            self.R3 = float(self.r3)
            self.R4 = float(self.r4)
            self.R5 = float(self.r5)
            self.R6 = float(self.r6)
            self.V1 = float(self.v1)
            self.I1 = self.V1 / self.R3
            self.I2 = (self.V1) * ((1 - (self.R4) + (self.R6) - (self.R4 * self.R6 / (self.R3 * self.R5)))) / (
                    -self.R4 - (self.R6 / self.R5) * (self.R4 + self.R1 + self.R5))
            self.I3 = (self.V1) * ((1 - (self.R4 + self.R6) / self.R3)) + self.R4 * self.I2 / -(self.R6)
            self.Multimeter_value_displayer.setText(
                    " R3 = {0}Ω \n V1 = {1}V \n I1 = {2}A".format(self.R3_value.text(), round(self.V1, 3),
                                                                  round(self.I3, 3)))

    def showR4properties(self):
            self.R1 = float(self.r1)
            self.R2 = float(self.r2)
            self.R3 = float(self.r3)
            self.R4 = float(self.r4)
            self.R5 = float(self.r5)
            self.R6 = float(self.r6)
            self.V1 = float(self.v1)
            self.I1 = self.V1 / self.R3
            self.I2 = (self.V1) * ((1 - (self.R4) + (self.R6) - (self.R4 * self.R6 / (self.R3 * self.R5)))) / (
                    -self.R4 - (self.R6 / self.R5) * (self.R4 + self.R1 + self.R5))
            self.I3 = (self.V1) * ((1 - (self.R4 + self.R6) / self.R3)) + self.R4 * self.I2 / -(self.R6)
            I = (self.I1 - self.I1)
            v4 = I * self.R4
            self.Multimeter_value_displayer.setText(" R3 = {0}Ω \n V3 = {1}V \n I3 = {2}A".format(self.R4_value.text(), round(v4, 3), round(I, 3)))

    def showR5properties(self):
            self.R1 = float(self.r1)
            self.R2 = float(self.r2)
            self.R3 = float(self.r3)
            self.R4 = float(self.r4)
            self.R5 = float(self.r5)
            self.R6 = float(self.r6)
            self.V1 = float(self.v1)
            self.I1 = self.V1 / self.R3
            self.I2 = (self.V1) * ((1 - (self.R4) + (self.R6) - (self.R4 * self.R6 / (self.R3 * self.R5)))) / (
                    -self.R4 - (self.R6 / self.R5) * (self.R4 + self.R1 + self.R5))
            self.I3 = (self.V1) * ((1 - (self.R4 + self.R6) / self.R3)) + self.R4 * self.I2 / -(self.R6)
            I = (self.I2 - self.I3)
            v5 = I * self.R5
            self.Multimeter_value_displayer.setText(
                    "R3 = {0}Ω \n V3 = {1}V \n I3 = {2}A".format(self.R5_value.text(), round(v5, 3), round(I, 3)))

    def showR6properties(self):
            self.R1 = float(self.r1)
            self.R2 = float(self.r2)
            self.R3 = float(self.r3)
            self.R4 = float(self.r4)
            self.R5 = float(self.r5)
            self.R6 = float(self.r6)
            self.V1 = float(self.v1)
            self.I1 = self.V1 / self.R3
            self.I2 = (self.V1) * ((1 - (self.R4) + (self.R6) - (self.R4 * self.R6 / (self.R3 * self.R5)))) / (
                    -self.R4 - (self.R6 / self.R5) * (self.R4 + self.R1 + self.R5))
            self.I3 = (self.V1) * ((1 - (self.R4 + self.R6) / self.R3)) + self.R4 * self.I2 / -(self.R6)
            I = (self.I1 - self.I3)
            v6 = I * self.R6
            self.Multimeter_value_displayer.setText(
                    "R3 = {0}Ω \n V3 = {1}V \n I3 = {2}A".format(self.R6_value.text(), round(v6, 3), round(I, 3)))

    def assign_Values(self):

            if self.V1_value.text()==" ":
                    self.v1 =="0"
            else:
                    self.v1 = self.V1_value.text()
            if self.R1_value.text()==" ":
                    self.r1 = 0
            else:
                    self.r1 = self.R1_value.text()
            if self.R2_value.text()==" ":
                     self.r2="0"
            else:
                     self.r2 = self.R2_value.text()

            if self.R3_value.text()==" ":
                    self.r3 =="0"
            else:
                    self.r3 = self.R3_value.text()
            if self.R4_value.text()==" ":
                    self.r4 = 0
            else:
                    self.r4 = self.R4_value.text()
            if self.R5_value.text()==" ":
                    self.r5="0"
            else:
                    self.r5 = self.R5_value.text()

            if self.R6_value.text()==" ":
                    self.r6="0"
            else:
                    self.r6 = self.R6_value.text()





    def simulate(self):

            if self.V1_top_label == 1 and self.YD_top_label == 1 and self.V1_bottom_label == 1 and self.YD_bottom_label == 1:
                    self.label.setText(
                            "                         Star-Delta Circuit        ")
                    self.label.setStyleSheet("QLabel{\n"
                                             "    \n"
                                             "    background-color: rgb(50, 75, 97);\n"
                                             "    color: white;\n"
                                             "}")
            else:
                    self.label.setText(
                            "                           (Circuit Not Complete)")
                    self.label.setStyleSheet("QLabel{\n"
                                             "    \n"
                                             "    background-color: rgb(50, 75, 97);\n"
                                             "    color: red;\n"
                                             "}")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Star - Delta Circuit"))
        self.label.setText(_translate("MainWindow", "                          Star - Delta Circuit"))
        self.pushButton_Lab_Manual.setText(_translate("MainWindow", "Lab Manual"))
        self.label_15.setText(_translate("MainWindow", "V"))
        self.label_17.setText(_translate("MainWindow", "R"))
        self.label_18.setText(_translate("MainWindow", "A"))
        self.label_19.setText(_translate("MainWindow", "COM"))
        self.R1_value.setPlaceholderText(_translate("MainWindow", "  Enter R1 Value"))
        self.label_32.setText(_translate("MainWindow", "Click a component to \n"
"change its value"))
        self.label_8.setText(_translate("MainWindow", "V1"))
        self.R2_value.setPlaceholderText(_translate("MainWindow", "  Enter R2 Value"))
        self.R6_value.setPlaceholderText(_translate("MainWindow", "  Enter R6 Value"))
        self.R3_value.setPlaceholderText(_translate("MainWindow", "  Enter R3 Value"))
        self.V1_value.setPlaceholderText(_translate("MainWindow", "  Enter V1 Value"))
        self.pushButton_Ok.setText(_translate("MainWindow", "Ok"))
        self.R5_value.setPlaceholderText(_translate("MainWindow", "  Enter R5 Value"))
        self.R4_value.setPlaceholderText(_translate("MainWindow", "  Enter R4 Value"))
        self.R1_Result.setText(_translate("MainWindow", "R1"))
        self.R3_Result.setText(_translate("MainWindow", "R3"))
        self.R4_Result.setText(_translate("MainWindow", "R4"))
        self.R5_Result.setText(_translate("MainWindow", "R5"))
        self.R6_Result.setText(_translate("MainWindow", "R6"))
        self.R2_Result.setText(_translate("MainWindow", "R2"))
        self.label_16.hide()
        self.label_24.hide()
        self.label_28.hide()
        self.label_29.hide()
        self.label_36.hide()

        self.listWidget_Drag_YD.setDragEnabled(True)
        self.listWidget_Drag_V1.setDragEnabled(True)

        self.listWidget_Drop_YD.setAcceptDrops(True)
        self.listWidget_Drop_V1.setAcceptDrops(True)

        YD = QListWidgetItem(QIcon("Star_Delta.PNG"), "")
        V1 = QListWidgetItem(QIcon("Battery_icon.png"), "")

        self.listWidget_Drag_YD.insertItem(1, YD)
        self.listWidget_Drag_V1.insertItem(1, V1)

        self.listWidget_Drag_YD.setIconSize(QSize(90, 100))
        self.listWidget_Drag_V1.setIconSize(QSize(40, 90))
        self.listWidget_Drop_YD.setIconSize(QSize(235, 245))
        self.listWidget_Drop_V1.setIconSize(QSize(50, 90))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = star_delta_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
